/**
 * Code content for IafViewerExMapboxStandalone example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
  "IafViewerExMapboxStandalone.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM } from '@dtplatform/iaf-viewer';
import { GIS_CONFIG } from './config';
import GisConfigPanel from '../toolkit/GisConfigPanel/GisConfigPanel';
import { loadCachedGisConfig } from '../toolkit/IafViewerExUtils';
import IafViewerExample from '../IafViewerExample/IafViewerExample';
import './IafViewerExMapboxStandalone.css';

class IafViewerExMapboxStandalone extends IafViewerExample {
  constructor(props) {
    super(props);
    
    // Load cached GIS config (token) from localStorage
    const cachedConfig = loadCachedGisConfig();
    
    // Merge cached values with default config
    const initialGisConfig = cachedConfig 
      ? { ...GIS_CONFIG, ...cachedConfig }
      : GIS_CONFIG;
    
    this.state = {
      ...this.state,
      gis: {
        enable: true,
        showToolbar: true,
        token: initialGisConfig.token,
        opacity: 1.0,
        dynamicRenderingZoom: 11,
        dynamicRenderingDistance: 1100,
        onIafMapReady: this.handleGisReady.bind(this),
        initial: {
          zoom: 15,
          pitch: 60,
          bearing: 0
        }
      },
      view3d: {
        opacity: 1.0,
        enable: false
      },
      view2d: {
        enable: false
      },
      ue: {
        enable: false
      },
      arcgis: {
        enable: false
      },
      showConfigPanel: props.showConfigPanel ?? false,
      eventLogs: [],
      enableEventLog: false,
      mapInstance: null
    };
  }

  handleGisReady(mapInstance) {
    this.addEventLog({
      type: 'onIafMapReady',
      mapInstance: mapInstance ? 'available' : 'null',
      info: {
        map: mapInstance?.map ? 'available' : 'null',
        containerId: mapInstance?.containerId,
        focusSelector: mapInstance?.focusSelector
      }
    });

    console.log('[Mapbox Standalone Viewer] GIS Map is ready!', mapInstance);

    this.mapInstance = mapInstance;
    this.setState({ mapInstance });

    if (mapInstance?.focusSelector) {
      const focusElement = document.querySelector(mapInstance.focusSelector);
      if (focusElement) {
        console.log('[Mapbox Standalone Viewer] GIS Map ready - focus selector available:', mapInstance.focusSelector);
      }
    }
  }


  handleGisPropertiesChange = (updatedGis) => {
    const gisWithHandler = {
      ...updatedGis,
      onIafMapReady: updatedGis.onIafMapReady ?? this.state.gis.onIafMapReady
    };
    this.setState({ gis: gisWithHandler });
    if (this.props.onGisPropertiesChange) {
      this.props.onGisPropertiesChange(gisWithHandler);
    }
  }

  render() {
    const serverUri = this.getActiveServerUri();

    const viewerProps = {
      ...this.getViewerCommonProps(),
      gis: this.state.gis,
      view2d: this.state.view2d,
      view3d: this.state.view3d,
      ue: this.state.ue,
      arcgis: this.state.arcgis,
      modelComposition: this.state.modelComposition,
      title: 'IafViewerExMapboxStandalone',
      enablePersistence: true,
      ...(serverUri && { serverUri })
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleGisPropertiesChange = this.props.onGisPropertiesChange ?? this.handleGisPropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-mapbox-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-mapbox-viewer-header',
          contentClassName: 'example-mapbox-viewer-header-content',
          backButtonClassName: 'example-mapbox-viewer-back-button',
          toggleClassName: 'example-mapbox-viewer-toggle',
          toggleButtonClassName: 'example-mapbox-viewer-toggle-button',
          headerTextClassName: 'example-mapbox-viewer-header-text',
          subtitleClassName: 'example-mapbox-viewer-subtitle',
          title: 'Mapbox Standalone Viewer',
          subtitle: 'Displays a Mapbox GIS map. Only GIS viewer is enabled.'
        })}
        {showConfigPanel && (
          <div className="example-mapbox-viewer-config-overlay" data-testid="gis-config-panel-container">
            <GisConfigPanel
              gis={this.state.gis}
              onGisChange={handleGisPropertiesChange}
              showAdvanced={true}
              onClose={handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              mapInstance={this.state.mapInstance}
            />
          </div>
        )}
        <div className="example-mapbox-viewer-content">
          <IafViewerDBM {...viewerProps} />
        </div>
      </div>
    );
  }
}

IafViewerExMapboxStandalone.propTypes = {
  ...IafViewerExample.propTypes,
  onGisPropertiesChange: PropTypes.func
};

export default IafViewerExMapboxStandalone;

`,
  "IafViewerExMapboxStandalone.css": `.example-mapbox-viewer-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.example-mapbox-viewer-header {
  padding: 12px 24px;
  border-bottom: 2px solid var(--examples-border-color, #e0e0e0);
  flex-shrink: 0;
  position: relative;
}

.example-mapbox-viewer-header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.example-mapbox-viewer-toggle {
  display: flex;
  gap: 8px;
  margin-left: auto;
  align-items: center;
}

.example-mapbox-viewer-toggle-button {
  background-color: transparent;
  color: var(--examples-text-secondary, #6d6e70);
  border: 1px solid var(--examples-border-color, #e0e0e0);
  padding: 6px 12px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.2s;
  white-space: nowrap;
}

.example-mapbox-viewer-toggle-button:hover {
  background-color: var(--examples-bg-color, #f5f5f5);
  border-color: var(--app-accent-color, #026bfd);
}

.example-mapbox-viewer-toggle-button.active {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border-color: var(--app-accent-color, #026bfd);
}

.example-mapbox-viewer-back-button {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}

.example-mapbox-viewer-back-button:hover {
  background-color: var(--app-accent-color, #026bfd);
  opacity: 0.9;
}

.example-mapbox-viewer-header-text {
  flex: 1;
  min-width: 0;
}

.example-mapbox-viewer-header h1 {
  margin: 0 0 4px 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--examples-text-primary, #333);
}

.example-mapbox-viewer-subtitle {
  margin: 0;
  font-size: 13px;
  color: var(--examples-text-secondary, #6d6e70);
}

.example-mapbox-viewer-content {
  flex: 1;
  overflow: hidden;
  max-height: calc(100% - var(--header-height, 80px));
  position: relative;
}

.example-mapbox-viewer-config-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 400px;
  max-width: 90vw;
  z-index: 1000;
  background: white;
  box-shadow: -2px 0 8px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

`,
  "config.js": `// GIS Configuration for Mapbox Standalone Viewer Example

// Default Mapbox token - should be replaced with actual token from environment or user input
export const GIS_CONFIG = {
  token: process.env.MAPBOX_TOKEN || "YOUR_MAPBOX_TOKEN_HERE" // Mapbox access token
};

`,
  "../IafViewerExample/IafViewerExample.jsx": `import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IafSession } from '@dtplatform/platform-api';

/**
 * Base class for all IafViewer example components
 * Provides common functionality like header height management, config panel toggling, server URI resolution,
 * event logging, model resolution, and common UI rendering helpers
 */
class IafViewerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewerSettings: this._loadViewerSettingsFromStorage()
    };
  }

  _loadViewerSettingsFromStorage() {
    if (typeof localStorage !== 'undefined' && localStorage.iafviewer_settings) {
      try {
        return JSON.parse(localStorage.iafviewer_settings);
      } catch (e) {
        return undefined;
      }
    }
    return undefined;
  }

  componentDidMount() {
    this.updateHeaderHeight();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.hideHeader !== this.props.hideHeader) {
      setTimeout(() => {
        this.updateHeaderHeight();
      }, 0);
    }
  }

  updateHeaderHeight = () => {
    const headerElement = this.headerRef;
    if (headerElement) {
      const headerHeight = headerElement.offsetHeight;
      const container = headerElement.parentElement;
      if (container) {
        container.style.setProperty('--header-height', \`\${headerHeight}px\`);
      }
    }
  }

  handleConfigToggle = () => {
    const currentState = this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
    const newState = !currentState;
    
    if (!this.props.onConfigToggle) {
      this.setState({ showConfigPanel: newState });
    }
    
    if (this.props.onConfigToggle) {
      this.props.onConfigToggle(newState);
    }
  }

  getActiveServerUri = () => {
    return this.props.serverUri || 
           (IafSession?.getConfig?.()?.graphicsServiceOrigin) ||
           null;
  }

  /**
   * Add an event to the event log (if event logging is enabled)
   * @param {Object} event - Event object to log
   */
  addEventLog = (event) => {
    if (!this.state.enableEventLog) {
      return;
    }
    this.setState(prevState => ({
      eventLogs: [...prevState.eventLogs, {
        ...event,
        timestamp: Date.now()
      }]
    }));
  }

  /**
   * Get the resolved showConfigPanel value (handles both controlled and uncontrolled components)
   * @returns {boolean} Whether the config panel should be shown
   */
  getShowConfigPanel = () => {
    return this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
  }

  /**
   * Resolve the model from props (selectedItems or direct model prop)
   * @returns {Object|null} The resolved model object or null
   */
  getModel = () => {
    return this.props.selectedItems?.selectedModel || this.props.model || null;
  }

  /**
   * Common viewer props (settings + saveSettings) for IafViewerDBM.
   * Spread into viewerProps so Cache Settings in the Settings panel can persist (e.g. isSingleChannelMode).
   * @returns {{ settings: Object|undefined, saveSettings: Function }}
   */
  getViewerCommonProps = () => ({
    settings: this.state.viewerSettings,
    saveSettings: this.saveSettingsCallback
  })

  /**
   * Callback to save viewer settings to localStorage and update state.
   * Pass to IafViewerDBM as saveSettings prop so Cache Settings button persists settings.
   */
  saveSettingsCallback = (settings) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.iafviewer_settings = JSON.stringify(settings);
    }
    this.setState({ viewerSettings: settings });
  }

  /**
   * Render the "No model" fallback message
   * @param {string} className - CSS class name for the container
   * @returns {JSX.Element} The "No model" fallback JSX
   */
  renderNoModelFallback = (className = 'example-viewer-no-model') => {
    return (
      <div className={className}>
        <p>No model selected. Please select a model from the Navigator to view this example.</p>
      </div>
    );
  }

  /**
   * Render the common header structure (Back button, View mode toggle, Title/Subtitle)
   * @param {Object} options - Header configuration options
   * @param {string} options.containerClassName - CSS class for the header container
   * @param {string} options.contentClassName - CSS class for the header content
   * @param {string} options.backButtonClassName - CSS class for the back button
   * @param {string} options.toggleClassName - CSS class for the view mode toggle container
   * @param {string} options.toggleButtonClassName - CSS class for the toggle buttons
   * @param {string} options.headerTextClassName - CSS class for the header text container
   * @param {string} options.subtitleClassName - CSS class for the subtitle (optional, defaults to headerTextClassName + '-subtitle')
   * @param {string} options.title - Header title
   * @param {string} options.subtitle - Header subtitle
   * @returns {JSX.Element} The header JSX
   */
  renderHeader = ({
    containerClassName,
    contentClassName,
    backButtonClassName,
    toggleClassName,
    toggleButtonClassName,
    headerTextClassName,
    subtitleClassName,
    title,
    subtitle
  }) => {
    if (this.props.hideHeader) {
      return null;
    }

    const finalSubtitleClassName = subtitleClassName || \`\${headerTextClassName}-subtitle\`;

    return (
      <div className={containerClassName} ref={(el) => { this.headerRef = el; }}>
        <div className={contentClassName}>
          <button 
            className={backButtonClassName}
            onClick={() => {
              if (this.props.onBackToList) {
                this.props.onBackToList();
              } else if (this.props.history) {
                this.props.history.push('/navigator?examplesView=true');
              } else {
                window.location.hash = '/navigator?examplesView=true';
              }
            }}
          >
            ← Back to Examples
          </button>
          {this.props.onViewModeToggle && (
            <div className={toggleClassName}>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'demo' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('demo')}
              >
                Demo
              </button>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'code' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('code')}
              >
                Code
              </button>
            </div>
          )}
          <div className={headerTextClassName}>
            <h1>{title}</h1>
            {subtitle && <p className={finalSubtitleClassName}>{subtitle}</p>}
          </div>
        </div>
      </div>
    );
  }
}

IafViewerExample.propTypes = {
  hideHeader: PropTypes.bool,
  showConfigPanel: PropTypes.bool,
  onConfigToggle: PropTypes.func,
  serverUri: PropTypes.string,
  selectedItems: PropTypes.object,
  model: PropTypes.object,
  history: PropTypes.object,
  onBackToList: PropTypes.func,
  viewMode: PropTypes.string,
  onViewModeToggle: PropTypes.func
};

export default IafViewerExample;

`
};
