/**
 * Code content for IafViewerExArcgisStandaloneViewer example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
  "IafViewerExArcgisStandaloneViewer.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM, IafEvmUtils } from '@dtplatform/iaf-viewer';
import { ARCGIS_CONFIG, INITIAL_POSITION_CAMERA } from './config';
import ArcGisConfigPanel from '../toolkit/ArcGisConfigPanel/ArcGisConfigPanel';
import IafViewerExample from '../IafViewerExample/IafViewerExample';
import { getSampleDistrictGraphics, getSampleZoomElements, getSampleZoomCommand, getSampleSlicedElements, getSampleThemeElements, getSampleLayers, loadCachedArcgisConfig, createOnIafMapReadyLog, getSampleArcGisModules } from '../toolkit/IafViewerExUtils';
import './IafViewerExArcgisStandaloneViewer.css';

class IafViewerExArcgisStandaloneViewer extends IafViewerExample {
  constructor(props) {
    super(props);
    
    // Load cached ArcGIS config (portalUrl, apiKey, model) from localStorage
    const cachedConfig = loadCachedArcgisConfig();
    
    // Merge cached values with default config
    const initialConfig = cachedConfig 
      ? { ...ARCGIS_CONFIG, ...cachedConfig } // Merge cached values with existing config
      : ARCGIS_CONFIG;
    
    this.state = {
      ...this.state,
      arcgis: {
        enable: true,
        config: initialConfig,
        // ArcGIS-specific properties - initialize with sample data
        slicedElements: getSampleSlicedElements(),
        themeElements: getSampleThemeElements(),
        graphics: getSampleDistrictGraphics(),
        zoomElements: getSampleZoomElements(),
        layers: getSampleLayers(),
        camera: INITIAL_POSITION_CAMERA,
        command: getSampleZoomCommand(),
        // Display properties
        displayMode: IafEvmUtils.EVMDisplayMode.FULLSCREEN,
        showToolbar: true,
        alignment: IafEvmUtils.EVMWidgetAlignment.LEFT_TOP,
        order: 7,
        margin: 0,
        // Callbacks
        eventHandler: this.handleArcgisEvent.bind(this),
        onIafMapReady: this.handleArcgisReady.bind(this)
      },
      view3d: {
        enable: false
      },
      view2d: {
        enable: false
      },
      ue: {
        enable: false
      },
      gis: {
        enable: false
      },
      showConfigPanel: props.showConfigPanel ?? false,
      eventLogs: [],
      enableEventLog: true, // Event logging enabled by default for demo
      mapInstance: null, // Will be set when viewer is ready
      onIafMapReadyLog: null // Special log for onIafMapReady callback data
    };
  }

  handleArcgisEvent(ev) {
    const eventName = ev?.eventName?.toLowerCase();
    
    // Add event to log
    this.addEventLog({
      type: 'eventHandler',
      eventName: ev?.eventName,
      payload: ev?.payload,
      fullEvent: ev
    });
    
    console.log('[ArcGIS Standalone Viewer] ArcGIS Event:', ev);
    
    switch (eventName) {
      case IafEvmUtils.EVM_EVENTS.VIEWER_READY:
        console.log('[ArcGIS Standalone Viewer] ArcGIS Viewer ready:', ev.payload);
        // Scene is ready - you can now perform operations like adding graphics, setting camera, etc.
        if (ev.payload?.ready) {
          console.log('[ArcGIS Standalone Viewer] Scene and SceneView are ready');
        }
        break;
        
      case IafEvmUtils.EVM_EVENTS.SELECTION_UPDATE:
        console.log('[ArcGIS Standalone Viewer] Element selected:', ev.payload);
        // Example: Handle district or building selection
        const elements = ev?.payload?.elements || [];
        elements.forEach(element => {
          console.log(\`  - \${element.elementType}: \${element.id}\`);
        });
        break;
        
      case IafEvmUtils.EVM_EVENTS.CAMERA_UPDATE:
        console.log('[ArcGIS Standalone Viewer] Camera updated:', ev.payload);
        break;
        
      case IafEvmUtils.EVM_EVENTS.POINTER_MOVE:
        // High-frequency event - typically not logged to avoid console spam
        break;
        
      case IafEvmUtils.EVM_EVENTS.POINTER_ENTER:
        console.log('[ArcGIS Standalone Viewer] Pointer enter:', ev.payload);
        break;
        
      case IafEvmUtils.EVM_EVENTS.POINTER_EXIT:
        console.log('[ArcGIS Standalone Viewer] Pointer exit:', ev.payload);
        break;
        
      case IafEvmUtils.EVM_EVENTS.LAYERS_UPDATE:
        console.log('[ArcGIS Standalone Viewer] Layers updated:', ev.payload);
        // Update layers property when layers change
        if (ev.payload?.visible) {
          this.setState(prevState => ({
            arcgis: {
              ...prevState.arcgis,
              layers: ev.payload.visible || []
            }
          }));
        }
        break;
        
      default:
        console.log('[ArcGIS Standalone Viewer] ArcGIS Event:', ev);
    }
  }

  handleArcgisReady(mapInstance) {
    // Extract available modules from arcgisModules
    const arcgisModules = mapInstance?.arcgisModules;
    const availableModules = arcgisModules ? Object.keys(arcgisModules).sort() : [];
    
    // Store onIafMapReady log data separately (not in event log)
    const onIafMapReadyLog = createOnIafMapReadyLog(mapInstance);

    console.log('[ArcGIS Standalone Viewer] ArcGIS Map is ready!', {
      mapInstance: mapInstance ? 'available' : 'not available',
      sceneView: mapInstance?.sceneView,
      scene: mapInstance?.scene,
      arcgisModules: arcgisModules ? 'available' : 'not available',
      availableModulesCount: availableModules.length,
      availableModules: availableModules,
      sampleModules: getSampleArcGisModules(arcgisModules)
    });

    // Store reference for potential use
    this.arcgisMapRef = mapInstance;
    
    // Update state to trigger re-render so mapInstance prop is available in ArcGisConfigPanel
    // Store onIafMapReady log separately (not in event log)
    this.setState({ mapInstance, onIafMapReadyLog });
    
    // Example: Access map instance methods
    if (mapInstance?.sceneView) {
      console.log('[ArcGIS Standalone Viewer] SceneView available - you can now use ArcGIS API methods');
      // Example: mapInstance.sceneView.setMapStyle("arcgis/light-gray");
    }

    // Sample graphics data inspired by applyDistrictsSymbologyAction()
    // This creates sample district label graphics similar to the PlatformReferenceApp implementation
    const sampleGraphics = getSampleDistrictGraphics();
    // This creates sample zoom elements following the pattern of zoomToOnly()
    const sampleZoomElements = getSampleZoomElements();
    // This creates sample zoom command following the exact pattern of zoomToOnly() (wrapped command object)
    const sampleZoomCommand = getSampleZoomCommand();

    console.log('[ArcGIS Standalone Viewer] Setting graphics:', {
      count: sampleGraphics.length,
      graphics: sampleGraphics,
      firstGraphic: sampleGraphics[0],
      hasUuid: sampleGraphics[0]?.uuid !== undefined
    });

    console.log('[ArcGIS Standalone Viewer] Setting zoomElements:', {
      count: sampleZoomElements.length,
      zoomElements: sampleZoomElements,
      firstZoomElement: sampleZoomElements[0]
    });

    console.log('[ArcGIS Standalone Viewer] Setting command:', {
      count: sampleZoomCommand.length,
      command: sampleZoomCommand,
      firstCommand: sampleZoomCommand[0]
    });

    // setTimeout(() => handleSampleGraphics(), 100);
    // setTimeout(() => handleInitialCamera(), 200);
    // setTimeout(() => handleSampleZoomElements(), 3000);
    // setTimeout(() => handleSampleZoomCommand(), 5000);
    // setTimeout(() => handleSampleSlicedElements(), 10000);
    // setTimeout(() => handleSampleThemeElements(), 15000);
  }


  handleArcgisPropertiesChange = (updatedArcgis) => {
    const arcgisWithHandler = {
      ...updatedArcgis,
      eventHandler: updatedArcgis.eventHandler ?? this.state.arcgis.eventHandler,
      onIafMapReady: updatedArcgis.onIafMapReady ?? this.state.arcgis.onIafMapReady
    };
    this.setState({ arcgis: arcgisWithHandler });
    if (this.props.onArcgisPropertiesChange) {
      this.props.onArcgisPropertiesChange(arcgisWithHandler);
    }
  }

  render() {
    const model = this.getModel();
    
    const viewerProps = {
      ...this.getViewerCommonProps(),
      arcgis: this.state.arcgis,
      view3d: this.state.view3d,
      view2d: this.state.view2d,
      ue: this.state.ue,
      gis: this.state.gis,
      enablePersistence: true,
    };

    const showConfigPanel = this.getShowConfigPanel();

    return (
      <div className="example-arcgis-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-arcgis-viewer-header',
          contentClassName: 'example-arcgis-viewer-header-content',
          backButtonClassName: 'example-arcgis-viewer-back-button',
          toggleClassName: 'example-arcgis-viewer-toggle',
          toggleButtonClassName: 'example-arcgis-viewer-toggle-button',
          headerTextClassName: 'example-arcgis-viewer-header-text',
          subtitleClassName: 'example-arcgis-viewer-subtitle',
          title: 'Standalone ArcGIS Viewer',
          subtitle: 'Minimal implementation with only ArcGIS rendering. No UE, ArcGIS Overview, or Photosphere.'
        })}
        {/* Config panel overlay */}
        {showConfigPanel && (
          <div className="example-arcgis-viewer-config-overlay" data-testid="arcgis-config-panel-container">
            <ArcGisConfigPanel
              arcgis={this.state.arcgis}
              onChange={this.handleArcgisPropertiesChange}
              showAdvanced={true}
              onClose={this.handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              onIafMapReadyLog={this.state.onIafMapReadyLog}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              mapInstance={this.state.mapInstance}
            />
          </div>
        )}
        <div className="example-arcgis-viewer-content">
          {model ? (
            <IafViewerDBM {...viewerProps} />
          ) : (
            this.renderNoModelFallback('example-arcgis-viewer-no-model')
          )}
        </div>
      </div>
    );
  }
}

IafViewerExArcgisStandaloneViewer.propTypes = {
  ...IafViewerExample.propTypes,
  onArcgisPropertiesChange: PropTypes.func
};

export default IafViewerExArcgisStandaloneViewer;

`,
  "IafViewerExArcgisStandaloneViewer.css": `.example-arcgis-viewer-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.example-arcgis-viewer-header {
  padding: 12px 24px;
  border-bottom: 2px solid var(--examples-border-color, #e0e0e0);
  flex-shrink: 0;
  position: relative;
}

.example-arcgis-viewer-header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.example-arcgis-viewer-toggle {
  display: flex;
  gap: 8px;
  margin-left: auto;
  align-items: center;
}

.example-arcgis-viewer-toggle-button {
  background-color: transparent;
  color: var(--examples-text-secondary, #6d6e70);
  border: 1px solid var(--examples-border-color, #e0e0e0);
  padding: 6px 12px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.2s;
  white-space: nowrap;
}

.example-arcgis-viewer-toggle-button:hover {
  background-color: var(--examples-bg-color, #f5f5f5);
  border-color: var(--app-accent-color, #026bfd);
}

.example-arcgis-viewer-toggle-button.active {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border-color: var(--app-accent-color, #026bfd);
}

.example-arcgis-viewer-back-button {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}

.example-arcgis-viewer-back-button:hover {
  background-color: var(--app-accent-color, #026bfd);
  opacity: 0.9;
}

.example-arcgis-viewer-header-text {
  flex: 1;
  min-width: 0;
}

.example-arcgis-viewer-header h1 {
  margin: 0 0 4px 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--examples-text-primary, #333);
}

.example-arcgis-viewer-subtitle {
  margin: 0;
  font-size: 13px;
  color: var(--examples-text-secondary, #6d6e70);
}

.example-arcgis-viewer-content {
  flex: 1;
  overflow: hidden;
  max-height: calc(100% - var(--header-height, 80px));
  position: relative;
}

.example-arcgis-viewer-no-model {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 40px;
  text-align: center;
}

.example-arcgis-viewer-no-model p {
  font-size: 16px;
  color: var(--examples-text-secondary, #6d6e70);
  margin: 0;
}

.example-arcgis-viewer-config-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 400px;
  max-width: 90vw;
  z-index: 1000;
  background: white;
  box-shadow: -2px 0 8px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.example-arcgis-viewer-config-placeholder {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 40px;
  text-align: center;
}

.example-arcgis-viewer-config-placeholder p {
  font-size: 16px;
  color: var(--examples-text-secondary, #6d6e70);
  margin: 0;
}

`,
  "config.js": `// ArcGIS Configuration for Standalone ArcGIS Viewer Example

// Initial camera position (Chicago example - can be customized)
export const INITIAL_POSITION_CAMERA = {
  position: { x: -87.667, y: 41.863, z: 3262.319 },
  rotation: { pitch: 50.063, yaw: 61.458 }
};

// Layer names matching PlatformReferenceApp
export const GIS_LAYER_NAMES = {
  BUILDINGS: "District Buildings - ChicagoBuildingsInDistricts",
  DISTRICTS: "Chicago POC Districts",
  BUILDINGS_LABEL_POINTS: "Chicago Building Label Points with Districts - Chicago Building Label Points with Districts",
  DISTRICTS_LABEL_POINTS: "Chicago Districts Label Points - Chicago Districts Centers 3d label height",
  EXCHANGE_BUILDING: "Exchange Building - Exchange Building",
  BULDINGS_POINTS: "ChicagoBuildingPoints_Districts",
};

// District names matching PlatformReferenceApp
export const GIS_DISTRICT_NAMES = {
  DOWNTOWN: "Downtown Business District",
  MILE: "Magnificient Mile",
  PARK: "Millenium Park",
  SLOOP: "South Loop",
  STREETV: "Streeterville",
  THEATRE: "Theatre District",
  WLOOP: "West Loop"
};

// Building names matching PlatformReferenceApp
export const GIS_BUILDING_NAMES = {
  TT: 'Chicago Title & Trust Building',
  Randolph: 'Randolph Tower',
  Dublin: 'Dublin Building',
  Cadillac: 'Cadillac Palace Theatre',
  Kemper: 'Kemper Building'
};

// Specificity values for layer prioritization
const SPECIFICITIES = {
  [GIS_LAYER_NAMES.DISTRICTS]: 100,
  [GIS_LAYER_NAMES.BUILDINGS]: 200,
};

// Helper functions to validate IDs
const isADistrictId = (id) => {
  return Object.values(GIS_DISTRICT_NAMES).includes(id);
};

const isABuildingId = (id) => {
  return Object.values(GIS_BUILDING_NAMES).includes(id);
};

// Layer information configuration
// This tells the GIS system how to identify and work with each layer
export const GIS_LAYERS = {
  [GIS_LAYER_NAMES.DISTRICTS]: {
    idField: "hl_districtname",
    isIdValidForLayer: isADistrictId,
    elementType: "district",
    highlight: {
      triggerEvent: 'pointer-move',
      highlightableIds: undefined // undefined == all ids
    },
    specificity: SPECIFICITIES[GIS_LAYER_NAMES.DISTRICTS]
  },
  [GIS_LAYER_NAMES.BUILDINGS]: {
    idField: "osm_id",
    idFieldType: "Integer",
    isIdValidForLayer: isABuildingId,
    elementType: "building",
    highlight: {
      triggerEvent: 'pointer-move',
      highlightableIds: undefined // undefined == all ids
    },
    specificity: SPECIFICITIES[GIS_LAYER_NAMES.BUILDINGS],
    relatedLayersField: {
      [GIS_LAYER_NAMES.DISTRICTS]: 'hl_district'
    },
    outFields: ["*"],
    popupTemplate: {
      title: \`{name}\`,
      content: [{
        type: "fields",
        fieldInfos: [{
          fieldName: 'hl_district',
          label: "District"
        }, {
          fieldName: 'hl_bldght',
          label: "Building Height",
          format: {
            places: 2,
            digitSeparator: true
          }
        }]
      }]
    }
  }
};

// ArcGIS Configuration - uses sample secret values from IafViewerExUtils
export const ARCGIS_CONFIG = {
  // Required ArcGIS configuration properties (from getSampleArcGisConfig)
  portalUrl: "YOUR_ARCGIS_PORTAL_URL_HERE", // e.g. https://gis.hlplanning.com/arcgis
  apiKey: "YOUR_ARCGIS_API_KEY_HERE",
  model: "YOUR_ARCGIS_MODEL_ID_HERE", // e.g. 6745f5a0f1df4812a26925c19fdab6f8
  
  // Optional configuration
  sceneWKID: 102100,
  shadows: false,
  groundOpacity: 1,
  popUpEnabled: false,
  highlightOnClick: false,
  highlightTheme: {
    color: [255, 255, 0, 1],
    haloColor: "white",
    haloOpacity: 0.9,
    fillOpacity: 0.2,
    shadowColor: "black",
    shadowOpacity: 0.5
  },
  // Camera position coordinates (dependent on the model's coordinate system)
  initialCameraPosition: INITIAL_POSITION_CAMERA,
  // Optional: Add components like zoom, compass
  components: ["zoom", "compass"],
  showBasemapGallery: true,
  // Hidden layers - layers that should be hidden by default
  hiddenLayers: [
    GIS_LAYER_NAMES.BUILDINGS_LABEL_POINTS,
    GIS_LAYER_NAMES.DISTRICTS_LABEL_POINTS
  ],
  // Layer information - tells the GIS system how to identify and work with each layer
  layerInfo: GIS_LAYERS
};

`,
  "../IafViewerExample/IafViewerExample.jsx": `import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IafSession } from '@dtplatform/platform-api';

/**
 * Base class for all IafViewer example components
 * Provides common functionality like header height management, config panel toggling, server URI resolution,
 * event logging, model resolution, and common UI rendering helpers
 */
class IafViewerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewerSettings: this._loadViewerSettingsFromStorage()
    };
  }

  _loadViewerSettingsFromStorage() {
    if (typeof localStorage !== 'undefined' && localStorage.iafviewer_settings) {
      try {
        return JSON.parse(localStorage.iafviewer_settings);
      } catch (e) {
        return undefined;
      }
    }
    return undefined;
  }

  componentDidMount() {
    this.updateHeaderHeight();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.hideHeader !== this.props.hideHeader) {
      setTimeout(() => {
        this.updateHeaderHeight();
      }, 0);
    }
  }

  updateHeaderHeight = () => {
    const headerElement = this.headerRef;
    if (headerElement) {
      const headerHeight = headerElement.offsetHeight;
      const container = headerElement.parentElement;
      if (container) {
        container.style.setProperty('--header-height', \`\${headerHeight}px\`);
      }
    }
  }

  handleConfigToggle = () => {
    const currentState = this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
    const newState = !currentState;
    
    if (!this.props.onConfigToggle) {
      this.setState({ showConfigPanel: newState });
    }
    
    if (this.props.onConfigToggle) {
      this.props.onConfigToggle(newState);
    }
  }

  getActiveServerUri = () => {
    return this.props.serverUri || 
           (IafSession?.getConfig?.()?.graphicsServiceOrigin) ||
           null;
  }

  /**
   * Add an event to the event log (if event logging is enabled)
   * @param {Object} event - Event object to log
   */
  addEventLog = (event) => {
    if (!this.state.enableEventLog) {
      return;
    }
    this.setState(prevState => ({
      eventLogs: [...prevState.eventLogs, {
        ...event,
        timestamp: Date.now()
      }]
    }));
  }

  /**
   * Get the resolved showConfigPanel value (handles both controlled and uncontrolled components)
   * @returns {boolean} Whether the config panel should be shown
   */
  getShowConfigPanel = () => {
    return this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
  }

  /**
   * Resolve the model from props (selectedItems or direct model prop)
   * @returns {Object|null} The resolved model object or null
   */
  getModel = () => {
    return this.props.selectedItems?.selectedModel || this.props.model || null;
  }

  /**
   * Common viewer props (settings + saveSettings) for IafViewerDBM.
   * Spread into viewerProps so Cache Settings in the Settings panel can persist (e.g. isSingleChannelMode).
   * @returns {{ settings: Object|undefined, saveSettings: Function }}
   */
  getViewerCommonProps = () => ({
    settings: this.state.viewerSettings,
    saveSettings: this.saveSettingsCallback
  })

  /**
   * Callback to save viewer settings to localStorage and update state.
   * Pass to IafViewerDBM as saveSettings prop so Cache Settings button persists settings.
   */
  saveSettingsCallback = (settings) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.iafviewer_settings = JSON.stringify(settings);
    }
    this.setState({ viewerSettings: settings });
  }

  /**
   * Render the "No model" fallback message
   * @param {string} className - CSS class name for the container
   * @returns {JSX.Element} The "No model" fallback JSX
   */
  renderNoModelFallback = (className = 'example-viewer-no-model') => {
    return (
      <div className={className}>
        <p>No model selected. Please select a model from the Navigator to view this example.</p>
      </div>
    );
  }

  /**
   * Render the common header structure (Back button, View mode toggle, Title/Subtitle)
   * @param {Object} options - Header configuration options
   * @param {string} options.containerClassName - CSS class for the header container
   * @param {string} options.contentClassName - CSS class for the header content
   * @param {string} options.backButtonClassName - CSS class for the back button
   * @param {string} options.toggleClassName - CSS class for the view mode toggle container
   * @param {string} options.toggleButtonClassName - CSS class for the toggle buttons
   * @param {string} options.headerTextClassName - CSS class for the header text container
   * @param {string} options.subtitleClassName - CSS class for the subtitle (optional, defaults to headerTextClassName + '-subtitle')
   * @param {string} options.title - Header title
   * @param {string} options.subtitle - Header subtitle
   * @returns {JSX.Element} The header JSX
   */
  renderHeader = ({
    containerClassName,
    contentClassName,
    backButtonClassName,
    toggleClassName,
    toggleButtonClassName,
    headerTextClassName,
    subtitleClassName,
    title,
    subtitle
  }) => {
    if (this.props.hideHeader) {
      return null;
    }

    const finalSubtitleClassName = subtitleClassName || \`\${headerTextClassName}-subtitle\`;

    return (
      <div className={containerClassName} ref={(el) => { this.headerRef = el; }}>
        <div className={contentClassName}>
          <button 
            className={backButtonClassName}
            onClick={() => {
              if (this.props.onBackToList) {
                this.props.onBackToList();
              } else if (this.props.history) {
                this.props.history.push('/navigator?examplesView=true');
              } else {
                window.location.hash = '/navigator?examplesView=true';
              }
            }}
          >
            ← Back to Examples
          </button>
          {this.props.onViewModeToggle && (
            <div className={toggleClassName}>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'demo' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('demo')}
              >
                Demo
              </button>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'code' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('code')}
              >
                Code
              </button>
            </div>
          )}
          <div className={headerTextClassName}>
            <h1>{title}</h1>
            {subtitle && <p className={finalSubtitleClassName}>{subtitle}</p>}
          </div>
        </div>
      </div>
    );
  }
}

IafViewerExample.propTypes = {
  hideHeader: PropTypes.bool,
  showConfigPanel: PropTypes.bool,
  onConfigToggle: PropTypes.func,
  serverUri: PropTypes.string,
  selectedItems: PropTypes.object,
  model: PropTypes.object,
  history: PropTypes.object,
  onBackToList: PropTypes.func,
  viewMode: PropTypes.string,
  onViewModeToggle: PropTypes.func
};

export default IafViewerExample;

`
};
