#!/usr/bin/env node

/**
 * Script to generate codeContent.js from actual source files
 * This ensures codeContent.js always matches the actual source files
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const COMPONENTS_DIR = path.join(__dirname, '../components');

// Define components to process and their files
const EXAMPLES = [
  {
    name: 'IafViewerExUeStandaloneViewer',
    files: [
      'IafViewerExUeStandaloneViewer.jsx',
      'IafViewerExUeStandaloneViewer.css',
      'config.js',
      '../IafViewerExample/IafViewerExample.jsx' // Parent base component
    ]
  },
  {
    name: 'IafViewerExArcgisStandaloneViewer',
    files: [
      'IafViewerExArcgisStandaloneViewer.jsx',
      'IafViewerExArcgisStandaloneViewer.css',
      'config.js',
      '../IafViewerExample/IafViewerExample.jsx' // Parent base component
    ]
  },
        {
          name: 'IafViewerExMapboxStandalone',
          files: [
            'IafViewerExMapboxStandalone.jsx',
            'IafViewerExMapboxStandalone.css',
            'config.js',
            '../IafViewerExample/IafViewerExample.jsx' // Parent base component
          ]
        },
        {
          name: 'IafViewerExGeoReferencedView3d',
          files: [
            'IafViewerExGeoReferencedView3d.jsx',
            'IafViewerExGeoReferencedView3d.css',
            'config.js',
            '../IafViewerExMapboxStandalone/config.js', // Include parent's GIS config
            '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.jsx', // Direct parent component
            '../IafViewerExample/IafViewerExample.jsx' // Base component
          ]
        },
        {
          name: 'IafViewerExClusteredGeoReferencedView3d',
          files: [
            'IafViewerExClusteredGeoReferencedView3d.jsx',
            'config.js',
            '../IafViewerExGeoReferencedView3d/IafViewerExGeoReferencedView3d.jsx',
            '../IafViewerExGeoReferencedView3d/IafViewerExGeoReferencedView3d.css',
            '../IafViewerExGeoReferencedView3d/config.js',
            '../IafViewerExMapboxStandalone/config.js',
            '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.jsx',
            '../IafViewerExample/IafViewerExample.jsx'
          ]
        },
        {
          name: 'IafViewerExGISProjectView',
          files: [
            'IafViewerExGISProjectView.jsx',
            'IafViewerExGISProjectView.css',
            '../IafViewerExMapboxStandalone/config.js',
            '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.jsx',
            '../IafViewerExample/IafViewerExample.jsx'
          ]
        }
];

function escapeTemplateLiteral(str) {
  // Escape backticks and ${} in template literals
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\${/g, '\\${');
}

export function generateCodeContentForComponent(componentName, files) {
  const codeContent = {};
  const componentDir = path.join(COMPONENTS_DIR, componentName);
  
  for (const filename of files) {
    // Handle relative paths (e.g., '../IafViewerExMapboxStandalone/config.js')
    // Resolve relative to the component's directory
    const filePath = filename.startsWith('../')
      ? path.resolve(componentDir, filename)
      : path.join(componentDir, filename);
    
    if (!fs.existsSync(filePath)) {
      console.warn(`⚠️  Warning: File not found: ${filePath}`);
      continue;
    }
    
    const content = fs.readFileSync(filePath, 'utf8');
    codeContent[filename] = escapeTemplateLiteral(content);
  }
  
  return codeContent;
}

function generateCodeContentFileForComponent(componentName, files) {
  const codeContent = generateCodeContentForComponent(componentName, files);
  const outputFile = path.join(COMPONENTS_DIR, componentName, 'codeContent.js');
  
  const output = `/**
 * Code content for ${componentName} example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
${Object.entries(codeContent).map(([filename, content]) => {
  return `  "${filename}": \`${content}\``;
}).join(',\n')}
};
`;

  fs.writeFileSync(outputFile, output, 'utf8');
  console.log(`✅ Generated ${outputFile}`);
  console.log(`   Included ${Object.keys(codeContent).length} file(s): ${files.join(', ')}`);
}

function generateAllCodeContent() {
  console.log('🔄 Generating code content for all examples...\n');
  
  for (const example of EXAMPLES) {
    generateCodeContentFileForComponent(example.name, example.files);
  }
  
  console.log(`\n✨ Successfully generated code content for ${EXAMPLES.length} example(s)`);
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateAllCodeContent();
}

