/**
 * Code content for IafViewerExClusteredGeoReferencedView3d example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
  "IafViewerExClusteredGeoReferencedView3d.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import IafViewerExGeoReferencedView3d from '../IafViewerExGeoReferencedView3d/IafViewerExGeoReferencedView3d';

/** One-line subtitle for IafViewerExamplesView fullscreen header (grid card uses long text in defaultExampleCategories). */
export const IafViewerExClusteredGeoReferencedView3dViewerSubtitle =
  'Geo-referenced 3D with clusteredModels for placement and outlines';

/**
 * Demo clusteredModels for a project: building groups, map centers, and outline clustering.
 * Irrelevant model ids are ignored for models not in the active project.
 */
const DEMO_CLUSTERED_MODELS = [
  {
    ids: ['69857ef69c176d4bc1e756f1'],
    title: 'Garden Pavilion',
    bearing: 180,
    center: { lng: 77.7186736529, lat: 13.1990670531 },
    altitude: 40,
  },
  {
    ids: [
      '6989e7b2c3aa852deb1c8527',
      '698acf7eaab0130f5abec895',
      '69928e8bd372a36f0ed0b549',
    ],
    bearing: 180,
    title: 'T2',
    center: { lng: 77.7160455491, lat: 13.1987226359 },
    altitude: 40,
  },
  {
    ids: ['6992843ad372a36f0ed0b2a2'],
    title: 'CUP',
    bearing: 180,
    center: { lng: 77.712639, lat: 13.196139 },
    altitude: 40,
  },
  {
    ids: ['69954014958e285828157aba'],
    title: 'East Gate House',
    bearing: 180,
    center: { lng: 77.7139044852, lat: 13.200347015 },
    altitude: 10,
  },
];

class IafViewerExClusteredGeoReferencedView3d extends IafViewerExGeoReferencedView3d {
  constructor(props) {
    super(props);
    this.state = {
      ...this.state,
      gis: {
        ...this.state.gis,
        initial: {
          ...this.state.gis.initial,
          zoom: 13,
          pitch: 60,
          bearing: 0
        },
        dynamicRenderingZoom: 13.5,
        dynamicRenderingDistance: 1400,
      },
      modelComposition: {
        ...this.state.modelComposition,
        clusteredModels: DEMO_CLUSTERED_MODELS,
      },
    };
  }

  getGeoRefViewerTitle() {
    return 'IafViewerExClusteredGeoReferencedView3d';
  }

  getGeoRefHeaderTitle() {
    return 'Clustered Geo-Referenced 3D Viewer';
  }

  getGeoRefHeaderSubtitle() {
    return 'Extends the geo-referenced 3D example with modelComposition.clusteredModels (per-cluster center, altitude, bearing; outline / GIS alignment).';
  }
}

IafViewerExClusteredGeoReferencedView3d.propTypes = {
  ...IafViewerExGeoReferencedView3d.propTypes,
};

export default IafViewerExClusteredGeoReferencedView3d;
`,
  "config.js": `// Configuration for Clustered Geo-Referenced 3D Viewer Example
`,
  "../IafViewerExGeoReferencedView3d/IafViewerExGeoReferencedView3d.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM, IafEvmUtils } from '@dtplatform/iaf-viewer';
import IafViewerExMapboxStandalone from '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone';
import GisConfigPanel from '../toolkit/GisConfigPanel/GisConfigPanel';
import View3dConfigPanel from '../toolkit/View3dConfigPanel/View3dConfigPanel';
import './IafViewerExGeoReferencedView3d.css';

/** One-line subtitle for IafViewerExamplesView fullscreen header (grid card uses long text in defaultExampleCategories). */
export const IafViewerExGeoReferencedView3dViewerSubtitle =
  'Mapbox GIS + 3D with geo-referencing; all project models, no clusteredModels filter.';

class IafViewerExGeoReferencedView3d extends IafViewerExMapboxStandalone {
  constructor(props) {
    super(props);
    
    // Add view3d to state (inherits all other state from parent)
    this.state = {
      ...this.state,
      view3d: {
        opacity: 1.0,
        enable: false
      },
      view2d: {
        enable: false
      },
      gis: {
        ...this.state.gis,
        showToolbar: false,
        dynamicRenderingZoom: 12,
        dynamicRenderingDistance: 1200,
        onIafMapReady: this.handleGisReady.bind(this),
        onFederatedModeChanged: this.handleFederatedModeChanged.bind(this),
        onReferenceModelChanged: this.handleReferenceModelChanged.bind(this),
        onElevationModeChanged: this.handleElevationModeChanged.bind(this),
        onOutlineLoaded: this.handleOutlineLoaded.bind(this),
        onModelSelect: this.handleModelSelect.bind(this),
        initial: {
          center: { lng: 77.7186736529, lat: 13.1990670531 }
        }
      },
      modelComposition: {
        defaultFederationType: "Project",
        initial: {
            Architectural: true,
            Structural: false,
            Mechanical: false,
            Electrical: false,
            Plumbing: false,
            FireProtection: false,
            Infrastructural: false,
            default: false
        },
        quality: 'low'
      },
      // Callback logs for display in config panel
      onIafMapReadyLog: null,
      onFederatedModeChangedLog: null,
      onReferenceModelChangedLog: null,
      onElevationModeChangedLog: null,
      onModelSelectLog: null,
      OnModelCompositionReadyCallback: this.handleModelCompositionReady.bind(this),
    };
  }

  _switchToOutlineMode() {
    setTimeout(() => {
      this.setState({
        gis: {
          ...this.state.gis,
          federatedMode: IafEvmUtils.EvmFederatedMode.Outline
        }
      });        
    }, 2000)
  }

  handleModelCompositionReady(modelType, firstLoad) {
    console.log('[Geo-Referenced 3D Viewer] Model composition ready:', modelType);
    if (modelType === '3d' && firstLoad) this._switchToOutlineMode();
  }

  handleOutlineLoaded() {
    console.log('[Geo-Referenced 3D Viewer] Outline loaded!');
    setTimeout(() => this.setState({
      view3d: {
        opacity: 1.0,
        enable: true
      }, 
      view2d: {
        enable: false
      }
    }), 1000);
  }

  handleGisReady(mapInstance) {
    console.log('[Geo-Referenced 3D Viewer] GIS Map is ready!', mapInstance);
    
    // Store callback data for display in config panel
    const onIafMapReadyLog = {
      mapInstance: mapInstance ? 'available' : 'null',
      map: mapInstance?.map ? 'available' : 'null',
      loaded: mapInstance?.loaded ? mapInstance.loaded() : false,
      timestamp: new Date().toISOString()
    };
    
    this._switchToOutlineMode();

    console.log('[Geo-Referenced 3D Viewer] GIS Map ready state!', this.state.gis);

    this.setupClickHandlers(mapInstance);
  }

  /**
   * Callback invoked when federated mode changes
   * @param {number} federatedMode - The new federated mode value (IafEvmUtils.EvmFederatedMode enum)
   */
  handleFederatedModeChanged(federatedMode) {
    // Get mode label using enum values
    let modeLabel = 'Unknown';
    if (federatedMode === IafEvmUtils.EvmFederatedMode.None) {
      modeLabel = 'None';
    } else if (federatedMode === IafEvmUtils.EvmFederatedMode.Outline) {
      modeLabel = 'Outline';
    } else if (federatedMode === IafEvmUtils.EvmFederatedMode.Hybrid) {
      modeLabel = 'Hybrid';
    } else if (federatedMode === IafEvmUtils.EvmFederatedMode.Dynamic) {
      modeLabel = 'Dynamic';
    } else if (federatedMode === IafEvmUtils.EvmFederatedMode.Markers) {
      modeLabel = 'Markers';
    }
    
    const logData = {
      federatedMode,
      modeLabel,
      enumValue: {
        None: IafEvmUtils.EvmFederatedMode.None,
        Outline: IafEvmUtils.EvmFederatedMode.Outline,
        Hybrid: IafEvmUtils.EvmFederatedMode.Hybrid,
        Dynamic: IafEvmUtils.EvmFederatedMode.Dynamic,
        Markers: IafEvmUtils.EvmFederatedMode.Markers
      },
      timestamp: new Date().toISOString()
    };
    
    console.log('[Geo-Referenced 3D Viewer] Federated mode changed:', logData);
    
    // Store callback data for display in config panel
    this.setState({ onFederatedModeChangedLog: logData });
    
    // Example: Update external UI state, sync with external systems, etc.
    // this.updateExternalFederatedModeState(federatedMode);
  }

  /**
   * Callback invoked when the primary (reference) model changes
   * @param {string} modelId - The new primary model ID (Platform file ID)
   */
  handleReferenceModelChanged(modelId) {
    const logData = {
      modelId,
      previousModelId: this.state.gis?.primaryModelId,
      timestamp: new Date().toISOString()
    };
    
    console.log('[Geo-Referenced 3D Viewer] Reference model changed:', logData);
    
    // Store callback data for display in config panel
    this.setState({ onReferenceModelChangedLog: logData });
    
    // Example: Update external UI state, sync with external systems, etc.
    // this.updateExternalPrimaryModelState(modelId);
    // this.loadModelMetadata(modelId);
  }

  /**
   * Callback invoked when elevation mode changes
   * @param {number} elevationMode - The new elevation mode value (IafEvmUtils.EvmElevationMode enum)
   */
  handleElevationModeChanged(elevationMode) {
    // Get mode label using enum values
    let modeLabel = 'Unknown';
    if (elevationMode === IafEvmUtils.EvmElevationMode.None) {
      modeLabel = 'None';
    } else if (elevationMode === IafEvmUtils.EvmElevationMode.QuickSurface) {
      modeLabel = 'QuickSurface';
    } else if (elevationMode === IafEvmUtils.EvmElevationMode.QuickUnderground) {
      modeLabel = 'QuickUnderground';
    } else if (elevationMode === IafEvmUtils.EvmElevationMode.Surface) {
      modeLabel = 'Surface';
    } else if (elevationMode === IafEvmUtils.EvmElevationMode.Blend) {
      modeLabel = 'Blend';
    } else if (elevationMode === IafEvmUtils.EvmElevationMode.Underground) {
      modeLabel = 'Underground';
    }
    
    const logData = {
      elevationMode,
      modeLabel,
      enumValue: {
        None: IafEvmUtils.EvmElevationMode.None,
        QuickSurface: IafEvmUtils.EvmElevationMode.QuickSurface,
        QuickUnderground: IafEvmUtils.EvmElevationMode.QuickUnderground,
        Surface: IafEvmUtils.EvmElevationMode.Surface,
        Blend: IafEvmUtils.EvmElevationMode.Blend,
        Underground: IafEvmUtils.EvmElevationMode.Underground
      },
      timestamp: new Date().toISOString()
    };
    
    console.log('[Geo-Referenced 3D Viewer] Elevation mode changed:', logData);
    
    // Store callback data for display in config panel
    this.setState({ onElevationModeChangedLog: logData });
    
    // Example: Update external UI state, sync with external systems, etc.
    // this.updateExternalElevationModeState(elevationMode);
  }

  /**
   * Callback invoked when a location marker for a model is selected (clicked)
   * @param {string} modelId - The Platform file ID of the selected model
   */
  handleModelSelect(modelId) {
    const logData = {
      modelId,
      timestamp: new Date().toISOString()
    };
    
    console.log('[Geo-Referenced 3D Viewer] Model selected:', logData);
    
    // Store callback data for display in config panel
    this.setState({ onModelSelectLog: logData });
    
    // Example: Update external UI state, show model details, etc.
    // this.showModelDetails(modelId);
    // this.updateExternalSelectionState(modelId);
  }

  setupClickHandlers = (iafmap) => {
    iafmap?.on('click', (e) => {
      const allFeatures = iafmap.queryRenderedFeatures(e.point);
      
      console.log('[Geo-Referenced 3D Viewer] Clicked features:', allFeatures.map(f => ({
        layerId: f.layer.id,
        layerType: f.layer.type,
        properties: f.properties
      })));

      // Handle location marker clicks
      const locationMarkerFeatures = allFeatures.filter(f => 
        f.layer.id === 'location-marker-image' || 
        f.layer.id === 'location-marker-title'
      );

      if (locationMarkerFeatures.length > 0) {
        const feature = locationMarkerFeatures[0];
        const modelId = feature.properties?.id;
        
        if (modelId === 'center-marker') return;

        this.handleModelClick(modelId, feature.layer.id, e);
      }
    });
  }

  /**
   * Handle location marker click - implement your custom logic here
   * 
   * @param {string} modelId - The Platform file ID / model ID from marker properties
   * @param {string} layerId - The Mapbox layer ID ('location-marker-image' or 'location-marker-title')
   * @param {Object} event - Mapbox click event with point, lngLat, etc.
   */
  handleModelClick(modelId, layerId, event) {
    // Example implementations:
    
    // 1. Link to Platform items
    // const platformItem = this.getPlatformItemByFileId(modelId);
    // if (platformItem) {
    //   this.showItemDetails(platformItem);
    // }

    // 2. Show custom Mapbox popup
    // if (window.mapboxgl && window.mapboxgl.Popup) {
    //   new window.mapboxgl.Popup()
    //     .setLngLat(event.lngLat)
    //     .setHTML(\`<b>Model ID:</b> \${modelId}<br><b>Layer ID:</b> \${layerId}\`)
    //     .addTo(iafmap);
    // }

    // 3. Update external UI state
    // this.props.onModelClick?.(modelId, event);

    // 4. Dispatch custom event for external listeners
    // window.dispatchEvent(new CustomEvent('model-clicked', {
    //   detail: { modelId, layerId, event }
    // }));

    // 5. Call parent component callback if provided
    // if (this.props.onModelClick) {
    //   this.props.onModelClick(modelId, layerId, event);
    // }

    console.log('[Geo-Referenced 3D Viewer] Handling model click - implement your logic here:', {
      modelId,
      layerId,
      coordinates: event.lngLat,
      screenPoint: event.point
    });
  }

  handleView3dPropertiesChange = (updatedView3d) => {
    this.setState({ view3d: updatedView3d });
    if (this.props.onView3dPropertiesChange) {
      this.props.onView3dPropertiesChange(updatedView3d);
    }
  }

  /** Subclasses (e.g. clustered variant) may override. */
  getGeoRefViewerTitle() {
    return 'IafViewerExGeoReferencedView3d';
  }

  /** Subclasses may override. */
  getGeoRefHeaderTitle() {
    return 'Geo-Referenced 3D Viewer';
  }

  /** Subclasses may override. */
  getGeoRefHeaderSubtitle() {
    return 'Displays 3D models on a Mapbox GIS map with geo-referencing. Both GIS and 3D viewer are enabled. Demonstrates model click handling for federated mode.';
  }

  render() {
    const model = this.getModel();
    const serverUri = this.getActiveServerUri();

    const viewerProps = {
      ...this.getViewerCommonProps(),
      gis: this.state.gis,
      view3d: this.state.view3d,
      view2d: this.state.view2d,
      ue: this.state.ue,
      arcgis: this.state.arcgis,
      modelComposition: this.state.modelComposition,
      enablePersistence: true,
      OnModelCompositionReadyCallback: this.state.OnModelCompositionReadyCallback,
      title: this.getGeoRefViewerTitle(),
      ...(serverUri && { serverUri }),
      ...(model && { model })
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleGisPropertiesChange = this.props.onGisPropertiesChange ?? this.handleGisPropertiesChange;
    const handleView3dPropertiesChange = this.props.onView3dPropertiesChange ?? this.handleView3dPropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-georef-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-georef-viewer-header',
          contentClassName: 'example-georef-viewer-header-content',
          backButtonClassName: 'example-georef-viewer-back-button',
          toggleClassName: 'example-georef-viewer-toggle',
          toggleButtonClassName: 'example-georef-viewer-toggle-button',
          headerTextClassName: 'example-georef-viewer-header-text',
          subtitleClassName: 'example-georef-viewer-subtitle',
          title: this.getGeoRefHeaderTitle(),
          subtitle: this.getGeoRefHeaderSubtitle()
        })}
        {showConfigPanel && (
          <div className="example-georef-viewer-config-overlay" data-testid="config-panel-container">
            <div className="example-georef-viewer-config-panels">
              <GisConfigPanel
                gis={this.state.gis}
                onGisChange={handleGisPropertiesChange}
                showAdvanced={true}
                onClose={handleConfigToggle}
                eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
                enableEventLog={this.state.enableEventLog}
                onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
                mapInstance={this.state.mapInstance}
                onIafMapReadyLog={this.state.onIafMapReadyLog}
                onFederatedModeChangedLog={this.state.onFederatedModeChangedLog}
                onReferenceModelChangedLog={this.state.onReferenceModelChangedLog}
                onElevationModeChangedLog={this.state.onElevationModeChangedLog}
                onModelSelectLog={this.state.onModelSelectLog}
              />
              <View3dConfigPanel
                view3d={this.state.view3d}
                onView3dChange={handleView3dPropertiesChange}
                showAdvanced={true}
                onClose={handleConfigToggle}
              />
            </div>
          </div>
        )}
        <div className="example-georef-viewer-content">
          {model ? (
            <IafViewerDBM {...viewerProps} />
          ) : (
            this.renderNoModelFallback('example-georef-viewer-no-model')
          )}
        </div>
      </div>
    );
  }
}

IafViewerExGeoReferencedView3d.propTypes = {
  ...IafViewerExMapboxStandalone.propTypes,
  onView3dPropertiesChange: PropTypes.func
};

export default IafViewerExGeoReferencedView3d;
`,
  "../IafViewerExGeoReferencedView3d/IafViewerExGeoReferencedView3d.css": `.example-georef-viewer-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.example-georef-viewer-header {
  padding: 12px 24px;
  border-bottom: 2px solid var(--examples-border-color, #e0e0e0);
  flex-shrink: 0;
  position: relative;
}

.example-georef-viewer-header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.example-georef-viewer-toggle {
  display: flex;
  gap: 8px;
  margin-left: auto;
  align-items: center;
}

.example-georef-viewer-toggle-button {
  background-color: transparent;
  color: var(--examples-text-secondary, #6d6e70);
  border: 1px solid var(--examples-border-color, #e0e0e0);
  padding: 6px 12px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.2s;
  white-space: nowrap;
}

.example-georef-viewer-toggle-button:hover {
  background-color: var(--examples-bg-color, #f5f5f5);
  border-color: var(--app-accent-color, #026bfd);
}

.example-georef-viewer-toggle-button.active {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border-color: var(--app-accent-color, #026bfd);
}

.example-georef-viewer-back-button {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}

.example-georef-viewer-back-button:hover {
  background-color: var(--app-accent-color, #026bfd);
  opacity: 0.9;
}

.example-georef-viewer-header-text {
  flex: 1;
  min-width: 0;
}

.example-georef-viewer-header h1 {
  margin: 0 0 4px 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--examples-text-primary, #333);
}

.example-georef-viewer-subtitle {
  margin: 0;
  font-size: 13px;
  color: var(--examples-text-secondary, #6d6e70);
}

.example-georef-viewer-content {
  flex: 1;
  overflow: hidden;
  max-height: calc(100% - var(--header-height, 80px));
  position: relative;
}

.example-georef-viewer-no-model {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 40px;
  text-align: center;
}

.example-georef-viewer-no-model p {
  font-size: 16px;
  color: var(--examples-text-secondary, #6d6e70);
  margin: 0;
}

.example-georef-viewer-config-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 800px;
  max-width: 90vw;
  z-index: 1000;
  background: white;
  box-shadow: -2px 0 8px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

.example-georef-viewer-config-panels {
  display: flex;
  flex-direction: row;
  height: 100%;
  width: 100%;
}

.example-georef-viewer-config-panels > .gis-config-panel,
.example-georef-viewer-config-panels > .view3d-config-panel {
  flex: 1;
  border-right: 1px solid var(--examples-border-color, #e0e0e0);
}

.example-georef-viewer-config-panels > .view3d-config-panel:last-child {
  border-right: none;
}

`,
  "../IafViewerExGeoReferencedView3d/config.js": `// Configuration for Geo-Referenced 3D Viewer Example
// This file is kept for future configuration needs

`,
  "../IafViewerExMapboxStandalone/config.js": `// GIS Configuration for Mapbox Standalone Viewer Example

// Default Mapbox token - should be replaced with actual token from environment or user input
export const GIS_CONFIG = {
  token: process.env.MAPBOX_TOKEN || "YOUR_MAPBOX_TOKEN_HERE" // Mapbox access token
};

`,
  "../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM } from '@dtplatform/iaf-viewer';
import { GIS_CONFIG } from './config';
import GisConfigPanel from '../toolkit/GisConfigPanel/GisConfigPanel';
import { loadCachedGisConfig } from '../toolkit/IafViewerExUtils';
import IafViewerExample from '../IafViewerExample/IafViewerExample';
import './IafViewerExMapboxStandalone.css';

class IafViewerExMapboxStandalone extends IafViewerExample {
  constructor(props) {
    super(props);
    
    // Load cached GIS config (token) from localStorage
    const cachedConfig = loadCachedGisConfig();
    
    // Merge cached values with default config
    const initialGisConfig = cachedConfig 
      ? { ...GIS_CONFIG, ...cachedConfig }
      : GIS_CONFIG;
    
    this.state = {
      ...this.state,
      gis: {
        enable: true,
        showToolbar: true,
        token: initialGisConfig.token,
        opacity: 1.0,
        dynamicRenderingZoom: 11,
        dynamicRenderingDistance: 1100,
        onIafMapReady: this.handleGisReady.bind(this),
        initial: {
          zoom: 15,
          pitch: 60,
          bearing: 0
        }
      },
      view3d: {
        opacity: 1.0,
        enable: false
      },
      view2d: {
        enable: false
      },
      ue: {
        enable: false
      },
      arcgis: {
        enable: false
      },
      showConfigPanel: props.showConfigPanel ?? false,
      eventLogs: [],
      enableEventLog: false,
      mapInstance: null
    };
  }

  handleGisReady(mapInstance) {
    this.addEventLog({
      type: 'onIafMapReady',
      mapInstance: mapInstance ? 'available' : 'null',
      info: {
        map: mapInstance?.map ? 'available' : 'null',
        containerId: mapInstance?.containerId,
        focusSelector: mapInstance?.focusSelector
      }
    });

    console.log('[Mapbox Standalone Viewer] GIS Map is ready!', mapInstance);

    this.mapInstance = mapInstance;
    this.setState({ mapInstance });

    if (mapInstance?.focusSelector) {
      const focusElement = document.querySelector(mapInstance.focusSelector);
      if (focusElement) {
        console.log('[Mapbox Standalone Viewer] GIS Map ready - focus selector available:', mapInstance.focusSelector);
      }
    }
  }


  handleGisPropertiesChange = (updatedGis) => {
    const gisWithHandler = {
      ...updatedGis,
      onIafMapReady: updatedGis.onIafMapReady ?? this.state.gis.onIafMapReady
    };
    this.setState({ gis: gisWithHandler });
    if (this.props.onGisPropertiesChange) {
      this.props.onGisPropertiesChange(gisWithHandler);
    }
  }

  render() {
    const serverUri = this.getActiveServerUri();

    const viewerProps = {
      ...this.getViewerCommonProps(),
      gis: this.state.gis,
      view2d: this.state.view2d,
      view3d: this.state.view3d,
      ue: this.state.ue,
      arcgis: this.state.arcgis,
      modelComposition: this.state.modelComposition,
      title: 'IafViewerExMapboxStandalone',
      enablePersistence: true,
      ...(serverUri && { serverUri })
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleGisPropertiesChange = this.props.onGisPropertiesChange ?? this.handleGisPropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-mapbox-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-mapbox-viewer-header',
          contentClassName: 'example-mapbox-viewer-header-content',
          backButtonClassName: 'example-mapbox-viewer-back-button',
          toggleClassName: 'example-mapbox-viewer-toggle',
          toggleButtonClassName: 'example-mapbox-viewer-toggle-button',
          headerTextClassName: 'example-mapbox-viewer-header-text',
          subtitleClassName: 'example-mapbox-viewer-subtitle',
          title: 'Mapbox Standalone Viewer',
          subtitle: 'Displays a Mapbox GIS map. Only GIS viewer is enabled.'
        })}
        {showConfigPanel && (
          <div className="example-mapbox-viewer-config-overlay" data-testid="gis-config-panel-container">
            <GisConfigPanel
              gis={this.state.gis}
              onGisChange={handleGisPropertiesChange}
              showAdvanced={true}
              onClose={handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              mapInstance={this.state.mapInstance}
            />
          </div>
        )}
        <div className="example-mapbox-viewer-content">
          <IafViewerDBM {...viewerProps} />
        </div>
      </div>
    );
  }
}

IafViewerExMapboxStandalone.propTypes = {
  ...IafViewerExample.propTypes,
  onGisPropertiesChange: PropTypes.func
};

export default IafViewerExMapboxStandalone;

`,
  "../IafViewerExample/IafViewerExample.jsx": `import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IafSession } from '@dtplatform/platform-api';

/**
 * Base class for all IafViewer example components
 * Provides common functionality like header height management, config panel toggling, server URI resolution,
 * event logging, model resolution, and common UI rendering helpers
 */
class IafViewerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewerSettings: this._loadViewerSettingsFromStorage()
    };
  }

  _loadViewerSettingsFromStorage() {
    if (typeof localStorage !== 'undefined' && localStorage.iafviewer_settings) {
      try {
        return JSON.parse(localStorage.iafviewer_settings);
      } catch (e) {
        return undefined;
      }
    }
    return undefined;
  }

  componentDidMount() {
    this.updateHeaderHeight();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.hideHeader !== this.props.hideHeader) {
      setTimeout(() => {
        this.updateHeaderHeight();
      }, 0);
    }
  }

  updateHeaderHeight = () => {
    const headerElement = this.headerRef;
    if (headerElement) {
      const headerHeight = headerElement.offsetHeight;
      const container = headerElement.parentElement;
      if (container) {
        container.style.setProperty('--header-height', \`\${headerHeight}px\`);
      }
    }
  }

  handleConfigToggle = () => {
    const currentState = this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
    const newState = !currentState;
    
    if (!this.props.onConfigToggle) {
      this.setState({ showConfigPanel: newState });
    }
    
    if (this.props.onConfigToggle) {
      this.props.onConfigToggle(newState);
    }
  }

  getActiveServerUri = () => {
    return this.props.serverUri || 
           (IafSession?.getConfig?.()?.graphicsServiceOrigin) ||
           null;
  }

  /**
   * Add an event to the event log (if event logging is enabled)
   * @param {Object} event - Event object to log
   */
  addEventLog = (event) => {
    if (!this.state.enableEventLog) {
      return;
    }
    this.setState(prevState => ({
      eventLogs: [...prevState.eventLogs, {
        ...event,
        timestamp: Date.now()
      }]
    }));
  }

  /**
   * Get the resolved showConfigPanel value (handles both controlled and uncontrolled components)
   * @returns {boolean} Whether the config panel should be shown
   */
  getShowConfigPanel = () => {
    return this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
  }

  /**
   * Resolve the model from props (selectedItems or direct model prop)
   * @returns {Object|null} The resolved model object or null
   */
  getModel = () => {
    return this.props.selectedItems?.selectedModel || this.props.model || null;
  }

  /**
   * Common viewer props (settings + saveSettings) for IafViewerDBM.
   * Spread into viewerProps so Cache Settings in the Settings panel can persist (e.g. isSingleChannelMode).
   * @returns {{ settings: Object|undefined, saveSettings: Function }}
   */
  getViewerCommonProps = () => ({
    settings: this.state.viewerSettings,
    saveSettings: this.saveSettingsCallback
  })

  /**
   * Callback to save viewer settings to localStorage and update state.
   * Pass to IafViewerDBM as saveSettings prop so Cache Settings button persists settings.
   */
  saveSettingsCallback = (settings) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.iafviewer_settings = JSON.stringify(settings);
    }
    this.setState({ viewerSettings: settings });
  }

  /**
   * Render the "No model" fallback message
   * @param {string} className - CSS class name for the container
   * @returns {JSX.Element} The "No model" fallback JSX
   */
  renderNoModelFallback = (className = 'example-viewer-no-model') => {
    return (
      <div className={className}>
        <p>No model selected. Please select a model from the Navigator to view this example.</p>
      </div>
    );
  }

  /**
   * Render the common header structure (Back button, View mode toggle, Title/Subtitle)
   * @param {Object} options - Header configuration options
   * @param {string} options.containerClassName - CSS class for the header container
   * @param {string} options.contentClassName - CSS class for the header content
   * @param {string} options.backButtonClassName - CSS class for the back button
   * @param {string} options.toggleClassName - CSS class for the view mode toggle container
   * @param {string} options.toggleButtonClassName - CSS class for the toggle buttons
   * @param {string} options.headerTextClassName - CSS class for the header text container
   * @param {string} options.subtitleClassName - CSS class for the subtitle (optional, defaults to headerTextClassName + '-subtitle')
   * @param {string} options.title - Header title
   * @param {string} options.subtitle - Header subtitle
   * @returns {JSX.Element} The header JSX
   */
  renderHeader = ({
    containerClassName,
    contentClassName,
    backButtonClassName,
    toggleClassName,
    toggleButtonClassName,
    headerTextClassName,
    subtitleClassName,
    title,
    subtitle
  }) => {
    if (this.props.hideHeader) {
      return null;
    }

    const finalSubtitleClassName = subtitleClassName || \`\${headerTextClassName}-subtitle\`;

    return (
      <div className={containerClassName} ref={(el) => { this.headerRef = el; }}>
        <div className={contentClassName}>
          <button 
            className={backButtonClassName}
            onClick={() => {
              if (this.props.onBackToList) {
                this.props.onBackToList();
              } else if (this.props.history) {
                this.props.history.push('/navigator?examplesView=true');
              } else {
                window.location.hash = '/navigator?examplesView=true';
              }
            }}
          >
            ← Back to Examples
          </button>
          {this.props.onViewModeToggle && (
            <div className={toggleClassName}>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'demo' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('demo')}
              >
                Demo
              </button>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'code' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('code')}
              >
                Code
              </button>
            </div>
          )}
          <div className={headerTextClassName}>
            <h1>{title}</h1>
            {subtitle && <p className={finalSubtitleClassName}>{subtitle}</p>}
          </div>
        </div>
      </div>
    );
  }
}

IafViewerExample.propTypes = {
  hideHeader: PropTypes.bool,
  showConfigPanel: PropTypes.bool,
  onConfigToggle: PropTypes.func,
  serverUri: PropTypes.string,
  selectedItems: PropTypes.object,
  model: PropTypes.object,
  history: PropTypes.object,
  onBackToList: PropTypes.func,
  viewMode: PropTypes.string,
  onViewModeToggle: PropTypes.func
};

export default IafViewerExample;

`
};
