export const Locator = {
  // Existing
  modelcomposerBtn: '[aria-label="Model Composer"]',
  annotationsBtn: '[id*="annotations-submenu"]',
  displayAccuracyBtn: 'xpath=//div[text()="Display Accuracy"]/ancestor::div[2]//input',
  annotationPanel: "annotations-panel",
  viewer3D: 'div[id^="view3d"] canvas',
  viewer2D: 'div[id^="view2d"] canvas',
  disciplines: 'div:has-text("Disciplines")',
  designerView: 'div[class^="SidePanel-module_sidePanelContent"] > div:nth-child(2)',
  designerMenu: 'button:has([data-testid="MoreVertIcon"])',
  autoCompose: 'input[name="enableAutoComposeTitle"]',

  // Toolbar
  resetViewToolbarIcon:        "//div[@aria-label='Reset View']",
  projectionToolbarIcon:       "//div[@aria-label='Projection']",
  navigationToolbarIcon:       "//div[@aria-label='Navigation']",
  measurementToolbarIcon:      "//div[@aria-label='Measurement']",
  cuttingPlaneToolbarIcon:     "//div[@aria-label='Cutting Plane']",
  twoDViewerToolbar:           "//div[@aria-label='2D Viewer']",
  focusModeToolbar:            "//div[@aria-label='Focus Mode']",
  settingsToolbarIcon:         "//div[@aria-label='Settings']",
  viewToolBarIcon:             "//div[@aria-label='View']",
  topViewIcon:                 "//span[text()='Top View']",
  bottomViewIcon:              "//span[text()='Bottom View']",
  leftViewIcon:                "//span[text()='Left View']",
  rightViewIcon:               "//span[text()='Right View']",
  frontViewIcon:               "//span[text()='Front View']",
  backViewIcon:                "//span[text()='Back View']",
  shadingToolbarIcon:          "//div[@aria-label='Shading']",
  fullShadingWithLineIcon:     "//span[text()='Full Shading, with Lines']",
  fullShadingNoLinesIcon:      "//span[text()='Full Shading, no Lines']",
  edges_LinesIcon:             "//span[text()='Edges & Lines']",
  glassViewIcon:               "//span[text()='Glass View']",
  utilitiesIcon:               "//div[@aria-label='Utilities']",
  isolateSelection:            "//span[text()='Isolate Selection']",
  hideSelection:               "//span[text()='Hide Selection']",
  showAll:                     "//span[text()='Show All']",

  // 2D Viewer
  twoDFullScreenIcon:          "//div[@aria-label='Full Screen']",
  twoDSelectFloorplan:         "//select[@name='Sheet Names']",
  twoDZoomIn:                  "//div[@aria-label='Zoom In']",
  twoDZoomOut:                 "//div[@aria-label='Zoom Out']",
  navigatorWidgetMinimizeIcon: "//i[normalize-space(@title)='Collapse panel']",

  // Cutting Plane
  standardPlanes:              "(//div[text()='Standard Planes'])[1]",
  standardPlanesToggleOn:      "(//div[text()='Standard Planes']//following::input[contains(@class,'PrivateSwitchBase-input')])[1]",

  // Model Composer
  modelComposer:               "//div[@aria-label='Model Composer']",
  modelComposer_Structural:    "//input[@name='Structural']/..//span[@class='MuiSwitch-thumb css-19gndve']",
  modelComposer_Mechanical:    "//input[@name='Mechanical']/..//span[@class='MuiSwitch-thumb css-19gndve']",
  modelComposer_Electrical:    "//input[@name='Electrical']/..//span[@class='MuiSwitch-thumb css-19gndve']",
  modelComposer_Plumbing:      "//input[@name='Plumbing']/..//span[@class='MuiSwitch-thumb css-19gndve']",

  // Annotations
  annotations:                 "//div[@aria-label='Annotations']",
  annotationsLine:             "//span[text()='Line']",
  annotationsCircle:           "//span[text()='Circle']",
  annotationsRectangle:        "//span[text()='Rectangle']",
  annotationsPolyline:         "//span[text()='Polyline']",
  annotationsPolygon:          "//span[text()='Polygon']",
  annotationsLeaderNote:       "//span[text()='Leader Note']",
  annotationsText:             "//span[text()='Text']",
  annotationsFreehand:         "//span[text()='Freehand']",
  annotationsExport:           "//span[text()='Export']",
  annotationsImport:           "//span[text()='Import']",
  annotationsDeleteAllMarkup:  "//div[text()='Delete All']/following::input[@type='checkbox'][1]",

  // GIS Viewer
  gisMenu:                       "//div[@aria-label='GIS Viewer']",
  enableGISToggle:               "//div[contains(text(),'Enable GIS')]/..//input[@type='checkbox']",
  gisInteractSectionHeader:      "//div[text()='Interact']",
  gisInteractZoomSliderValue:    "//div[text()='Zoom']/..//div[@class='IafSlider-module_range-value-box__60Ke8']",
  gisInteractPitchSliderValue:   "//div[text()='Pitch']/..//div[@class='IafSlider-module_range-value-box__60Ke8']",
  gisInteractBearingSliderValue: "//div[text()='Bearing']/..//div[@class='IafSlider-module_range-value-box__60Ke8']",
  gisAppearanceSectionHeader:    "//div[text()='Appearance']",
  gisStyleDropdown:              "//select[contains(@class,'IafDropdown-module_select-component') and @name='Style']",
  gisElevationModeDropdown:      "//select[@name='Elevation Mode']",
  gisGlobeViewToggle:            "//div[text()='Globe View']/..//input[@type='checkbox']",
  gisShowMarkersToggle:          "//div[text()='Show Markers']/..//input[@type='checkbox']",
  gisFederatedModelSection:      "//div[contains(@class,'IafSubHeader-module_list-item')]/..//div[contains(text(),'Federated')]",
  gisHorizontalAlignmentToggle:  "//div[contains(text(),'Horizontal Alignment')]/..//input[@type='checkbox']",
  gisBearingSliderValue:         "//div[text()='Bearing']/..//div[@class='IafSlider-module_range-value__tY7ul']",
  gisLongitudeSliderValue:       "//div[text()='Longitude']/..//div[@class='IafSlider-module_range-value__tY7ul']",
  gisLatitudeSliderValue:        "//div[text()='Latitude']/..//div[@class='IafSlider-module_range-value__tY7ul']",
  gisSearchTextBox:              "//input[@type='text' and @placeholder='Search']",
  gisVerticalAlignmentToggle:    "//div[contains(text(),'Vertical Alignment')]/..//input[@type='checkbox']",
  gisTerrainHeightSliderValue:   "//div[contains(text(),'Terrain Height')]/..//div[@class='IafSlider-module_range-value__tY7ul']",
  gisResetButton:                "//p[text()='Reset']",
}