export const Locator = {
  modelcomposerBtn: '[aria-label="Model Composer"]',
  gisViewerBtn: '[aria-label="GIS Viewer"]',
  gisViewer: 'div[id^="gis"] canvas',
  annotationsBtn: '[id*="annotations-submenu"]',
  displayAccuracyBtn: 'xpath=//div[text()="Display Accuracy"]/ancestor::div[2]//input',
  annotationPanel: "annotations-panel",
  viewer3D: 'div[id^="view3d"] canvas',
  viewer2D: 'div[id^="view2d"] canvas',
  disciplines: 'div:has-text("Disciplines")',
  designerView: 'div[class^="SidePanel-module_sidePanelContent"] > div:nth-child(2)',
  designerMenu: 'button:has([data-testid="MoreVertIcon"])',
  autoCompose: 'input[name="enableAutoComposeTitle"]',
  helpers: '//div[text()="Helpers"]',

  federatedPanelTitle: '(//div[contains(@class,"IafHeading-module_list-item-title")])[2]',

  searchPhysicalModels: '.MuiInputBase-input.MuiInput-input',

  federatedThreeDots: 'li:has(p[withsubtext="Federated"]) button',
  federatedSThreeDots: 'li:has(p[withsubtext*="-S-"]) button',
  federatedAThreeDots: 'li:has(p[withsubtext*="-A-"]) button',
  federatedHThreeDots: 'xpath=//p[contains(@withsubtext,"-H")]/ancestor::li//button',
  federatedEThreeDots: 'xpath=//p[contains(@withsubtext,"-E")]/ancestor::li//button',
  federatedPThreeDots: 'li:has(p[withsubtext*="-P"]) button',
  federatedFThreeDots: 'xpath=//p[contains(@withsubtext,"-F")]/ancestor::li//button',

  menuRename: '//li[@role="menuitem" and contains(.,"Rename")]',
  menuSwitchToLoadEverything: '//li[@role="menuitem" and contains(.,"Switch to Load Everything")]',
  menuShowAll: '//li[@role="menuitem" and contains(.,"Show All")]',
  menuHideAll: '//li[@role="menuitem" and contains(.,"Hide All")]',

  menuLoad: '//li[@role="menuitem" and contains(.,"Load")]',
  menuShow: '//li[@role="menuitem" and contains(.,"Show")]',
  menuHide: '//li[@role="menuitem" and contains(.,"Hide")]',
  menuRenameSubItem: '//li[@role="menuitem" and contains(.,"Rename")]',

  twoDDragArea: '(//div[@aria-label="Drag Area"])[1]',
  twoDFullScreen: '(//div[@aria-label="Full Screen"])[1]',
  twoDHalfScreen: '(//div[@aria-label="Half Screen"])[1]',
  twoDZoomIn: '(//div[@aria-label="Zoom In"])[1]',
  twoDZoomOut: '(//div[@aria-label="Zoom Out"])[1]',

  resetView: '[aria-label="Reset View"]',
  projection: '[aria-label="Projection"]',
  viewToolbar: '[aria-label="View"]',
  viewer2DToolbar: '[aria-label="2D Viewer"]',
  viewer3DToolbar: '[aria-label="3D Viewer"]',
  focusMode: '//div[@aria-label="Focus Mode"]',

  topView: '//span[text()="Top View"]',
  bottomView: '//span[text()="Bottom View"]',
  leftView: '//span[text()="Left View"]',
  rightView: '//span[text()="Right View"]',
  frontView: '//span[text()="Front View"]',
  backView: '//span[text()="Back View"]',

  shadingToolbar: '[aria-label="Shading"]',
  fullShadingWithLines: '//span[text()="Full Shading, with Lines"]',
  fullShadingNoLines: '//span[text()="Full Shading, no Lines"]',
  edgesAndLines: '//span[text()="Edges & Lines"]',
  glassView: '//span[text()="Glass View"]',

  elementSearchToolbar: "//i[@class='fas fa-search']",
  elementCategorySelect: '//div[text()="ElementCategory"]/ancestor::div[1]//div[contains(@class,"ipa-select__control")]',
  elementTypeSelect: '//div[text()="ElementType"]/ancestor::div[1]//div[contains(@class,"ipa-select__control")]',

  searchIcon: '.fas.fa-search',
  filterIcon: '.fas.fa-filter',
  listIconContainer: '.navigator-bottom-data',
  listIconGlyph: '.fa-list',
  resultContentColumn: '.content-column',
  selectAllCheckbox: '.header-column.checkbox input[type="checkbox"]',
  rowAncestorWithCheckbox: 'ancestor::*[.//input[@type="checkbox"]][1]',
  collapsePanelIcons: '.bottom-panel__icons--right-icons',

  resultRowCheckbox: '.content-column input[type="checkbox"]',

  disciplinesContainer: '//div[normalize-space()="Disciplines"]/following-sibling::div[1]',
  disabledDisciplineCheckbox: 'input[type="checkbox"][name]:disabled',

  modelSpinner: '#modelSpinner',
  compositionApplyingNotification: 'text=Please wait while the model composition settings are being applied',
  compositionAccuracyOverrideNotification: 'text=The visibility of some of the selected elements is overriden by the Model Layers Composition Settings',

  plg1764ArchLinkedFileThreeDots: 'li:has(p[withsubtext*="ARCH_AR-T2-ASM-ENCL_2024"]) button',
  plg1764IntPartitionLinkedFileThreeDots: 'li:has(p[withsubtext*="INT_PARTITION_GFC CORE_R1_2024"]) button',

  disciplineVisibilityUpdatingNotification: 'text=The visibility of disciplines is being updated',
  privilegedDisciplineTooltip: 'text=This has been designated as a privileged discipline',

  devToolsPanelHeading: 'text=Dev Tools',
  devToolsGltfToolsLink: 'text=GLTF Tools',

  setupProjectNameInput: '//*[normalize-space(text())="Name"]/following::input[1]',
  setupProjectShortNameInput: '//*[normalize-space(text())="Short Name"]/following::input[1]',
  setupProjectDescriptionInput: '//*[normalize-space(text())="Description"]/following::input[1]',
  setupProjectMultiModelCheckbox: "//label[text()='Enable multiple model support']/..//input[@type='checkbox']",
  navigatorRailIcon: 'text=2D/3D',
  adminRailIcon: 'text=Admin',
  adminRailIconGlyph: 'i.fa-user-shield',
  manageModelMenuItem: 'text=Manage Model',
  navigatorMenuTile: 'text=Navigator',
  mapboxTempTokenConfigHeading: 'text=Mapbox temp token config',

  cuttingPlaneToolbar: '[aria-label="Cutting Plane"]',

  standardPlanes: '(//div[text()="Standard Planes"])[1]',
  standardPlanesToggle: '(//div[text()="Standard Planes"]//following::input[contains(@class,"PrivateSwitchBase-input")])[1]',
  topPlaneSlider: '(//div[text()="Top plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  bottomPlaneSlider: '(//div[text()="Bottom plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  frontPlaneSlider: '(//div[text()="Front plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  backPlaneSlider: '(//div[text()="Back plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  leftPlaneSlider: '(//div[text()="Left plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  rightPlaneSlider: '(//div[text()="Right plane:"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  showPlanesToggle: '(//div[text()="Show planes"]//following::input[contains(@class,"PrivateSwitchBase-input")])[1]',

  focusedPlanes: '(//div[text()="Focused Planes"])[1]',
  focusedPlanesToggle: '(//div[text()="Focused Planes"]//following::input[contains(@class,"PrivateSwitchBase-input")])[1]',
  focusedPlanesSizeSlider: '(//div[text()="Focused Planes"]/following::div[text()="Size"]/following::span[contains(@class,"MuiSlider-root")])[1]',
  changeFocusBtn: '//p[text()="Change Focus"]',

  annotationsToolbar: '//div[@aria-label="Annotations"]',
  annotationsCheckDistance: '//span[text()="Check Distance"]',
  annotationsLine: '//span[text()="Line"]',
  annotationsCircle: '//span[text()="Circle"]',
  annotationsRectangle: '//span[text()="Rectangle"]',
  annotationsPolyline: '//span[text()="Polyline"]',
  annotationsPolygon: '//span[text()="Polygon"]',
  annotationsLeaderNote: '//span[text()="Leader Note"]',
  annotationsText: '//span[text()="Text"]',
  annotationsFreehand: '//span[text()="Freehand"]',
  annotationsExport: '//span[text()="Export"]',
  annotationsImport: '//span[text()="Import"]',
  annotationsDeleteAllMarkup: '//input[@name="deleteAllMarkup"]',

  gisMenu: '//div[@aria-label="GIS Viewer"]',
  enableGISToggle: '//div[contains(text(),"Enable GIS")]/..//input[@type="checkbox"]',
  gisInteractSectionHeader: '//div[text()="Interact"]',
  gisInteractZoomSliderValue: '//div[text()="Zoom"]/following::input[@type="range"][1]',
  gisInteractPitchSliderValue: '//div[text()="Pitch"]/..//div[@class="IafSlider-module_range-value-box__60Ke8"]',
  gisInteractBearingSliderValue: '//div[text()="Bearing"]/..//div[@class="IafSlider-module_range-value-box__60Ke8"]',
  gisAppearanceSectionHeader: '//div[text()="Appearance"]',
  gisStyleDropdown: '//select[contains(@class,"IafDropdown-module_select-component") and @name="Style"]',
  gisLayerDropdown: '//select[contains(@class,"IafDropdown-module_select-component") and @name="Layer"]',
  gisElevationModeDropdown: '//select[@name="Elevation Mode"]',
  gisGlobeViewToggle: '//div[text()="Globe View"]/..//input[@type="checkbox"]',
  gisShowMarkersToggle: '//div[text()="Show Markers"]/..//input[@type="checkbox"]',
  gisFederatedModelSection: '//div[contains(@class,"IafSubHeader-module_list-item")]/..//div[contains(text(),"Federated")]',
  gisFederatedSectionHeader: '//div[text()="Federated"]',
  gisFederatedModeDropdown: '//select[contains(@class,"IafDropdown-module_select-component") and @name="Federated Mode"]',
  gisFederatedIPUTExchangeItem: '//div[contains(@class,"IafSubHeader-module_list-item-sub-title") and text()="IPUT Exchange"]',
  gisOutlineShowModelToggle: '//div[contains(@class,"IafSwitch-module_switch-title") and text()="Show Model"]/..//input[@type="checkbox"]',
  gisHorizontalAlignmentTogglebutton: '//div[contains(text(),"Horizontal Alignment")]/..//input[@type="checkbox"]',
  gisBearingSliderValue: '//div[text()="Bearing"]/..//div[@class="IafSlider-module_range-value__tY7ul"]',
  gisLongitudeSliderValue: '//div[text()="Longitude"]/..//div[@class="IafSlider-module_range-value__tY7ul"]',
  gisLatitudeSliderValue: '//div[text()="Latitude"]/..//div[@class="IafSlider-module_range-value__tY7ul"]',
  gisSearchTextBox: '//input[@type="text" and @placeholder="Search"]',
  gisVerticalAlignmentTogglebutton: '//div[contains(text(),"Vertical Alignment")]/..//input[@type="checkbox"]',
  gisTerrainHeightSliderValue: '//div[contains(text(),"Terrain Height")]/..//div[@class="IafSlider-module_range-value__tY7ul"]',
  gisResetButton: '//p[text()="Reset"]',
  gisReferenceModelDropdown: '//select[contains(@class,"IafDropdown-module_select-component") and @name="Reference Model"]',
  gisBearingInput: '//div[text()="Bearing"]/following::input[@type="range"][1]',
  gisLongitudeInput: '//div[text()="Longitude"]/following::input[@type="range"][1]',
  gisLatitudeInput: '//div[text()="Latitude"]/following::input[@type="range"][1]',
  gisTerrainHeightInput: '//div[contains(text(),"Terrain Height")]/following::input[@type="range"][1]',

  elementMenuIcon: 'i.inv-icon-assets',
  workflowNavLink: 'a[href="#/workflow"] span.menu-item',
  workflowFilterToggle: 'div.navigator-bottom-filter i.fa-filter',
  workflowSelectDropdown: 'text=Select a workflow...',
  workflowGoLiveBtn: '[aria-label="Go Live"]',
  workflowStopLiveBtn: '[aria-label="Stop Live"]',
  workflowLiveToast: 'text=The workflow visualisation is now live',
  workflowActionLogPanel: '.log-container',
  workflowActionLogEntries: '.log-container li',
  workflowClockDisplay: '.time-display',
}

export const Notifications = {
    focusPlane : "You may want to select an element to enable focused planes",
    gisConfigUpdated: "GIS configuration has been updated",
    gisAlignmentConfirmPrompt: "press ENTER to confirm",
}
