/**
 * Code content for IafViewerExUeStandaloneViewer example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
  "IafViewerExUeStandaloneViewer.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM, IafEvmUtils } from '@dtplatform/iaf-viewer';
import { UE_CONFIG } from './config';
import UeConfigPanel from '../toolkit/UeConfigPanel/UeConfigPanel';
import IafViewerExample from '../IafViewerExample/IafViewerExample';
import './IafViewerExUeStandaloneViewer.css';
import { getSampleUeCommand, getSampleUeZoomElements, loadCachedUeConfig } from '../toolkit/IafViewerExUtils';

class IafViewerExUeStandaloneViewer extends IafViewerExample {
  constructor(props) {
    super(props);
    
    // Load cached UE config (server and app) from localStorage
    const cachedConfig = loadCachedUeConfig();
    
    // Merge cached values with default config
    const initialConfig = cachedConfig 
      ? { ...UE_CONFIG, ...cachedConfig } // Merge cached server/app with existing config
      : UE_CONFIG;
    
    this.state = {
      ...this.state,
      ue: {
        enable: true,
        config: initialConfig,
              zoomElements: getSampleUeZoomElements(),
              command: getSampleUeCommand(),
        eventHandler: this.handleUeEvent.bind(this),
        onUeReady: this.handleUeReady.bind(this),
        displayMode: IafEvmUtils.EVMDisplayMode.FULLSCREEN,
        showToolbar: true,
        alignment: IafEvmUtils.EVMWidgetAlignment.RIGHT_BOTTOM,
        order: 7,
        margin: 0
      },
      view3d: {
        enable: false
      },
      view2d: {
        enable: false
      },
      gis: {
        enable: false
      },
      showConfigPanel: props.showConfigPanel ?? false,
      eventLogs: [], // Array to store events for display in config panel
      enableEventLog: false, // Event logging disabled by default as it slows down the app
      sendCommand: null // Will be set when viewer is ready
    };
  }

  handleUeEvent(ev) {
    const eventName = ev?.eventName?.toLowerCase();
    
    // Add event to log
    this.addEventLog({
      type: 'eventHandler',
      eventName: ev?.eventName,
      payload: ev?.payload,
      fullEvent: ev
    });
    
    switch (eventName) {
      case IafEvmUtils.EVM_EVENTS.SELECTION_UPDATE:
        console.log('[UE Standalone Viewer] Element selected:', ev.payload);
        break;
        
      case IafEvmUtils.EVM_EVENTS.CAMERA_UPDATE:
        console.log('[UE Standalone Viewer] Camera updated:', ev.payload);
        break;
        
      case IafEvmUtils.EVM_EVENTS.COMMAND_RECEIVED:
        console.log('[UE Standalone Viewer] Command received:', ev.payload);
        break;
        
      default:
        console.log('[UE Standalone Viewer] UE Event:', ev);
    }
  }

  handleUeReady({ iframe, containerId, config, sendCommand, focusSelector, viewerReady, error }) {
    // Add ready event to log
    this.addEventLog({
      type: 'onUeReady',
      viewerReady,
      error,
      info: {
        iframe: iframe ? 'available' : 'null',
        containerId,
        config,
        sendCommand: typeof sendCommand === 'function' ? 'available' : 'null',
        focusSelector
      }
    });

    console.log('[UE Standalone Viewer] UE Viewer is ready!', {
      iframe,
      containerId,
      config,
      sendCommand: typeof sendCommand === 'function' ? 'available' : 'not available',
      focusSelector,
      viewerReady
    });

    // Store references for potential use
    this.ueViewerRef = {
      iframe,
      containerId,
      config,
      sendCommand,
      focusSelector
    };
    
    // Update state to trigger re-render so sendCommand prop is available in UeConfigPanel
    this.setState({ sendCommand });

    // Example: Send an initial command when viewer is ready
    // This demonstrates how to use the sendCommand method
    if (sendCommand && typeof sendCommand === 'function') {
      console.log('[UE Standalone Viewer] UE Viewer ready - sendCommand method is available');
      // You can send initial commands here if needed
      // Example: sendCommand({ commandName: 'zoom_to', params: { elementId: '123' } });
    }

    // Example: Focus the viewer programmatically
    if (focusSelector) {
      const focusElement = document.querySelector(focusSelector);
      if (focusElement) {
        console.log('[UE Standalone Viewer] UE Viewer ready - focus selector available:', focusSelector);
        // Uncomment to auto-focus when ready:
        // focusElement.focus();
      }
    }
  }


  handleUePropertiesChange = (updatedUe) => {
    const ueWithHandler = {
      ...updatedUe,
      eventHandler: updatedUe.eventHandler ?? this.state.ue.eventHandler,
      onUeReady: updatedUe.onUeReady ?? this.state.ue.onUeReady
    };
    this.setState({ ue: ueWithHandler });
    if (this.props.onUePropertiesChange) {
      this.props.onUePropertiesChange(ueWithHandler);
    }
  }

  render() {
    const model = this.getModel();
    
    const viewerProps = {
      ...this.getViewerCommonProps(),
      ue: this.state.ue,
      view3d: this.state.view3d,
      view2d: this.state.view2d,
      gis: this.state.gis,
      enablePersistence: true,
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleUePropertiesChange = this.props.onUePropertiesChange ?? this.handleUePropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-ue-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-ue-viewer-header',
          contentClassName: 'example-ue-viewer-header-content',
          backButtonClassName: 'example-ue-viewer-back-button',
          toggleClassName: 'example-ue-viewer-toggle',
          toggleButtonClassName: 'example-ue-viewer-toggle-button',
          headerTextClassName: 'example-ue-viewer-header-text',
          subtitleClassName: 'example-ue-viewer-subtitle',
          title: 'Standalone UE Viewer',
          subtitle: 'Minimal implementation with only UE rendering. No ArcGIS, ArcGIS Overview, or Photosphere.'
        })}
        {/* Config panel overlay - always visible when showConfigPanel is true */}
        {showConfigPanel && (
          <div className="example-ue-viewer-config-overlay" data-testid="ue-config-panel-container">
            <UeConfigPanel
              ue={this.state.ue}
              onChange={handleUePropertiesChange}
              showAdvanced={true}
              onClose={handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              sendCommand={this.state.sendCommand}
            />
          </div>
        )}
        <div className="example-ue-viewer-content">
          {model ? (
            <IafViewerDBM {...viewerProps} />
          ) : (
            this.renderNoModelFallback('example-ue-viewer-no-model')
          )}
        </div>
      </div>
    );
  }
}

IafViewerExUeStandaloneViewer.propTypes = {
  ...IafViewerExample.propTypes,
  onUePropertiesChange: PropTypes.func
};

export default IafViewerExUeStandaloneViewer;

`,
  "IafViewerExUeStandaloneViewer.css": `.example-ue-viewer-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  width: 100%;
  overflow: hidden;
}

.example-ue-viewer-header {
  padding: 12px 24px;
  border-bottom: 2px solid var(--examples-border-color, #e0e0e0);
  flex-shrink: 0;
  position: relative;
}

.example-ue-viewer-header-content {
  display: flex;
  align-items: center;
  gap: 16px;
}

.example-ue-viewer-toggle {
  display: flex;
  gap: 8px;
  margin-left: auto;
  align-items: center;
}

.example-ue-viewer-toggle-button {
  background-color: transparent;
  color: var(--examples-text-secondary, #6d6e70);
  border: 1px solid var(--examples-border-color, #e0e0e0);
  padding: 6px 12px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.2s;
  white-space: nowrap;
}

.example-ue-viewer-toggle-button:hover {
  background-color: var(--examples-bg-color, #f5f5f5);
  border-color: var(--app-accent-color, #026bfd);
}

.example-ue-viewer-toggle-button.active {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border-color: var(--app-accent-color, #026bfd);
}

.example-ue-viewer-back-button {
  background-color: var(--app-accent-color, #026bfd);
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.2s;
  white-space: nowrap;
  flex-shrink: 0;
}

.example-ue-viewer-back-button:hover {
  background-color: var(--app-accent-color, #026bfd);
  opacity: 0.9;
}

.example-ue-viewer-header-text {
  flex: 1;
  min-width: 0;
}

.example-ue-viewer-header h1 {
  margin: 0 0 4px 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--examples-text-primary, #333);
}

.example-ue-viewer-subtitle {
  margin: 0;
  font-size: 13px;
  color: var(--examples-text-secondary, #6d6e70);
}

.example-ue-viewer-content {
  flex: 1;
  overflow: hidden;
  max-height: calc(100% - var(--header-height, 80px));
  position: relative;
}

.example-ue-viewer-no-model {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  padding: 40px;
  text-align: center;
}

.example-ue-viewer-no-model p {
  font-size: 16px;
  color: var(--examples-text-secondary, #6d6e70);
  margin: 0;
}

.example-ue-viewer-config-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  width: 400px;
  max-width: 90vw;
  z-index: 1000;
  background: white;
  box-shadow: -2px 0 8px rgba(0, 0, 0, 0.15);
  overflow: hidden;
  display: flex;
  flex-direction: column;
}

`,
  "config.js": `// UE Configuration for Standalone UE Viewer Example

// Uses sample config from IafViewerExUtils
export const UE_CONFIG = {
  server: "YOUR_SERVER_URL_HERE", // e.g. https://connector.eagle3dstreaming.com
  app: "YOUR_APP_URL_HERE" // e.g. /v6/eyJvd25lciI6ImludmljYXJhZGVtbyIsImFwcE5hbWUiOiJDaGljYWdvQXBwIi................................................."
};

`,
  "../IafViewerExample/IafViewerExample.jsx": `import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IafSession } from '@dtplatform/platform-api';

/**
 * Base class for all IafViewer example components
 * Provides common functionality like header height management, config panel toggling, server URI resolution,
 * event logging, model resolution, and common UI rendering helpers
 */
class IafViewerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewerSettings: this._loadViewerSettingsFromStorage()
    };
  }

  _loadViewerSettingsFromStorage() {
    if (typeof localStorage !== 'undefined' && localStorage.iafviewer_settings) {
      try {
        return JSON.parse(localStorage.iafviewer_settings);
      } catch (e) {
        return undefined;
      }
    }
    return undefined;
  }

  componentDidMount() {
    this.updateHeaderHeight();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.hideHeader !== this.props.hideHeader) {
      setTimeout(() => {
        this.updateHeaderHeight();
      }, 0);
    }
  }

  updateHeaderHeight = () => {
    const headerElement = this.headerRef;
    if (headerElement) {
      const headerHeight = headerElement.offsetHeight;
      const container = headerElement.parentElement;
      if (container) {
        container.style.setProperty('--header-height', \`\${headerHeight}px\`);
      }
    }
  }

  handleConfigToggle = () => {
    const currentState = this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
    const newState = !currentState;
    
    if (!this.props.onConfigToggle) {
      this.setState({ showConfigPanel: newState });
    }
    
    if (this.props.onConfigToggle) {
      this.props.onConfigToggle(newState);
    }
  }

  getActiveServerUri = () => {
    return this.props.serverUri || 
           (IafSession?.getConfig?.()?.graphicsServiceOrigin) ||
           null;
  }

  /**
   * Add an event to the event log (if event logging is enabled)
   * @param {Object} event - Event object to log
   */
  addEventLog = (event) => {
    if (!this.state.enableEventLog) {
      return;
    }
    this.setState(prevState => ({
      eventLogs: [...prevState.eventLogs, {
        ...event,
        timestamp: Date.now()
      }]
    }));
  }

  /**
   * Get the resolved showConfigPanel value (handles both controlled and uncontrolled components)
   * @returns {boolean} Whether the config panel should be shown
   */
  getShowConfigPanel = () => {
    return this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
  }

  /**
   * Resolve the model from props (selectedItems or direct model prop)
   * @returns {Object|null} The resolved model object or null
   */
  getModel = () => {
    return this.props.selectedItems?.selectedModel || this.props.model || null;
  }

  /**
   * Common viewer props (settings + saveSettings) for IafViewerDBM.
   * Spread into viewerProps so Cache Settings in the Settings panel can persist (e.g. isSingleChannelMode).
   * @returns {{ settings: Object|undefined, saveSettings: Function }}
   */
  getViewerCommonProps = () => ({
    settings: this.state.viewerSettings,
    saveSettings: this.saveSettingsCallback
  })

  /**
   * Callback to save viewer settings to localStorage and update state.
   * Pass to IafViewerDBM as saveSettings prop so Cache Settings button persists settings.
   */
  saveSettingsCallback = (settings) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.iafviewer_settings = JSON.stringify(settings);
    }
    this.setState({ viewerSettings: settings });
  }

  /**
   * Render the "No model" fallback message
   * @param {string} className - CSS class name for the container
   * @returns {JSX.Element} The "No model" fallback JSX
   */
  renderNoModelFallback = (className = 'example-viewer-no-model') => {
    return (
      <div className={className}>
        <p>No model selected. Please select a model from the Navigator to view this example.</p>
      </div>
    );
  }

  /**
   * Render the common header structure (Back button, View mode toggle, Title/Subtitle)
   * @param {Object} options - Header configuration options
   * @param {string} options.containerClassName - CSS class for the header container
   * @param {string} options.contentClassName - CSS class for the header content
   * @param {string} options.backButtonClassName - CSS class for the back button
   * @param {string} options.toggleClassName - CSS class for the view mode toggle container
   * @param {string} options.toggleButtonClassName - CSS class for the toggle buttons
   * @param {string} options.headerTextClassName - CSS class for the header text container
   * @param {string} options.subtitleClassName - CSS class for the subtitle (optional, defaults to headerTextClassName + '-subtitle')
   * @param {string} options.title - Header title
   * @param {string} options.subtitle - Header subtitle
   * @returns {JSX.Element} The header JSX
   */
  renderHeader = ({
    containerClassName,
    contentClassName,
    backButtonClassName,
    toggleClassName,
    toggleButtonClassName,
    headerTextClassName,
    subtitleClassName,
    title,
    subtitle
  }) => {
    if (this.props.hideHeader) {
      return null;
    }

    const finalSubtitleClassName = subtitleClassName || \`\${headerTextClassName}-subtitle\`;

    return (
      <div className={containerClassName} ref={(el) => { this.headerRef = el; }}>
        <div className={contentClassName}>
          <button 
            className={backButtonClassName}
            onClick={() => {
              if (this.props.onBackToList) {
                this.props.onBackToList();
              } else if (this.props.history) {
                this.props.history.push('/navigator?examplesView=true');
              } else {
                window.location.hash = '/navigator?examplesView=true';
              }
            }}
          >
            ← Back to Examples
          </button>
          {this.props.onViewModeToggle && (
            <div className={toggleClassName}>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'demo' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('demo')}
              >
                Demo
              </button>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'code' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('code')}
              >
                Code
              </button>
            </div>
          )}
          <div className={headerTextClassName}>
            <h1>{title}</h1>
            {subtitle && <p className={finalSubtitleClassName}>{subtitle}</p>}
          </div>
        </div>
      </div>
    );
  }
}

IafViewerExample.propTypes = {
  hideHeader: PropTypes.bool,
  showConfigPanel: PropTypes.bool,
  onConfigToggle: PropTypes.func,
  serverUri: PropTypes.string,
  selectedItems: PropTypes.object,
  model: PropTypes.object,
  history: PropTypes.object,
  onBackToList: PropTypes.func,
  viewMode: PropTypes.string,
  onViewModeToggle: PropTypes.func
};

export default IafViewerExample;

`
};
