/**
 * Code content for IafViewerExGISProjectView example
 * Exported as strings for display in the examples viewer
 * 
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by examples/scripts/generateCodeContent.js
 * which reads the actual source files and generates this module with their contents as strings.
 * 
 * To regenerate: npm run generate-code-content
 * This runs automatically as part of: npm run build-dev
 */

export const CODE_CONTENT = {
  "IafViewerExGISProjectView.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM, IafEvmUtils } from '@dtplatform/iaf-viewer';
import IafViewerExMapboxStandalone from '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone';
import GisConfigPanel from '../toolkit/GisConfigPanel/GisConfigPanel';
import '../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.css';
import './IafViewerExGISProjectView.css';

/**
 * Mapbox GIS example focused on a multi-building project: same clusteredModels / federation
 * setup as the standalone Mapbox example, with federated Outline mode and GIS callbacks
 * wired for debugging. Derived from {@link IafViewerExMapboxStandalone}.
 */
class IafViewerExGISProjectView extends IafViewerExMapboxStandalone {
  constructor(props) {
    super(props);

    this.state = {
      ...this.state,
      toolbarSize: 'none',
      gis: {
        ...this.state.gis,      
        enable: true,
        initial: {
          zoom: 14,
          pitch: 0,
          bearing: 0
        },
        showToolbar: false,
        dynamicRenderingZoom: 13,
        dynamicRenderingDistance: 1300,
        federatedMode: IafEvmUtils.EvmFederatedMode.None,
        onIafMapReady: this.handleGisReady.bind(this),
        onFederatedModeChanged: (mode) => {
          console.log('[GIS Project View] gis.onFederatedModeChanged', mode);
        },
        onReferenceModelChanged: (modelId) => {
          console.log('[GIS Project View] gis.onReferenceModelChanged', modelId);
        },
        onElevationModeChanged: (elevationMode) => {
          console.log('[GIS Project View] gis.onElevationModeChanged', elevationMode);
        },
        onModelSelect: (modelId) => {
          console.log('[GIS Project View] gis.onModelSelect', modelId);
        },
        onOutlineLoaded: () => {
          console.log('[GIS Project View] gis.onOutlineLoaded');
          this.focusOnPrimaryBuilding();
        },
        onLongitudeChange: (modelIds, value) => {
          console.log('[GIS Project View] gis.onLongitudeChange', modelIds, value);
        },
        onLatitudeChange: (modelIds, value) => {
          console.log('[GIS Project View] gis.onLatitudeChange', modelIds, value);
        },
        onBearingChange: (modelIds, value) => {
          console.log('[GIS Project View] gis.onBearingChange', modelIds, value);
        },
        onAltitudeChange: (modelIds, value) => {
          console.log('[GIS Project View] gis.onAltitudeChange', modelIds, value);
        },
      },
      modelComposition: {
        defaultFederationType: "Project",
        initial: {
            Architectural: true,
            Structural: false,
            Mechanical: false,
            Electrical: false,
            Plumbing: false,
            FireProtection: false,
            Infrastructural: false,
            default: false
        },
        // In the real app - the clusteredModels for a project would represent the set of buildings or models that are part of the project.
        // 
        // For iafviewer examples based on IafViewerExGeoReferencedView3d - clusteredModels would probably be shared between 
        // multiple projects for demonstration purposes. Having irrelvant models ids may won't harm the active project setup 
        // as iafviewer picks on the models that belong to the active project 
        clusteredModels: [
            {
                ids: ["69857ef69c176d4bc1e756f1"],
                title: "Garden Pavilion",
                bearing: 180,
                center: { lng: 77.7186736529, lat: 13.1990670531 },
                altitude: 0,
            },
            {
                ids: [
                    "6989e7b2c3aa852deb1c8527", // T2-ELEC-Federated
                    "698acf7eaab0130f5abec895", // T2-FAS-Federated
                    "69928e8bd372a36f0ed0b549", // T2-HVAC-Federated
                ],
                bearing: 180,
                title: "T2",
                center: { lng: 77.7160455491, lat: 13.1987226359 },
                altitude: 0,
            },
            {
                ids: ["6992843ad372a36f0ed0b2a2"],
                title: "CUP",
                bearing: 180,
                center: { lng: 77.712639, lat: 13.196139 },
                altitude: 0,
            },
            {
                ids: ["69954014958e285828157aba"],
                title: "East Gate House",
                bearing: 180,
                center: { lng: 77.7139044852, lat: 13.200347015 },
                altitude: 0,
            },
        ],                      
        quality: 'low'
      },      
    };
  }

  focusOnPrimaryBuilding = () => {
    const primaryBuilding = this.state.mapInstance?.getPrimaryBuilding?.();
    if (primaryBuilding) {
      console.log('[GIS Project View] focusOnPrimaryBuilding primaryBuilding', primaryBuilding);
      this.state.mapInstance?.setCenter([primaryBuilding.primaryModel.longitude, primaryBuilding.primaryModel.latitude]);
    } else {
      console.warn('[GIS Project View] primaryBuilding not available, using default center');
      this.state.mapInstance?.setCenter([77.7160455491, 13.1987226359]);
    }
  };

  /**
   * Map proxy {@link IafMapBoxGLProxy#resetAll} — same GIS reset path as the viewer toolbar Home when GIS is on.
   */
  handleGisHomeReset = async () => {
    const proxy = this.state.mapInstance;
    if (!proxy || typeof proxy.resetAll !== 'function') {
      console.warn('[GIS Project View] Map proxy is not ready or resetAll is unavailable');
      return;
    }
    try {
      await proxy.resetAll();
      console.log('[GIS Project View] resetAll completed (custom Home button)');
      this.addEventLog({
        type: 'resetAll',
        mapInstance: 'available',
        info: { source: 'IafViewerExGISProjectView Home button' }
      });
    } catch (err) {
      console.error('[GIS Project View] resetAll failed', err);
    }
  };

  handleGisReady(mapInstance) {
    console.log('[GIS Project View] GIS map ready (project / federation context)', mapInstance);

    // Same as IafViewerExMapboxStandalone: keep proxy on instance + state so GIS callbacks can use it
    this.setState({ mapInstance });

    this.addEventLog({
      type: 'onIafMapReady',
      mapInstance: mapInstance ? 'available' : 'null',
      info: {
        map: mapInstance?.map ? 'available' : 'null',
        containerId: mapInstance?.containerId,
        focusSelector: mapInstance?.focusSelector
      }
    });
    
    const restrictedMethods = mapInstance?.getRestrictedMethods?.();
    console.log('[GIS Project View] restrictedMethods', restrictedMethods);

    // Reset camera for a consistent demo view (map proxy: setPitch / setBearing / setZoom)
    if (mapInstance) {
      try {
        // mapInstance.setCenter([77.7160455491, 13.1987226359]);
        // mapInstance.setPitch(0);
        // mapInstance.setBearing(0);
        // mapInstance.setZoom(14.5);
      } catch (err) {
        console.warn('[GIS Project View] Failed to reset pitch/bearing/zoom on map ready', err);
      }
    } else {
      console.warn('[GIS Project View] mapInstance not available');
    }

    setTimeout(() => this.setState((prev) =>
      prev.gis.federatedMode === IafEvmUtils.EvmFederatedMode.Outline
        ? { mapInstance }
        : {
            mapInstance,
            gis: { ...prev.gis, federatedMode: IafEvmUtils.EvmFederatedMode.Outline }
          }
    ), 1000);
  }

  handleGisPropertiesChange = (updatedGis) => {
    const gisWithHandler = {
      ...updatedGis,
      onIafMapReady: updatedGis.onIafMapReady ?? this.state.gis.onIafMapReady,
      onFederatedModeChanged: updatedGis.onFederatedModeChanged ?? this.state.gis.onFederatedModeChanged,
      onReferenceModelChanged: updatedGis.onReferenceModelChanged ?? this.state.gis.onReferenceModelChanged,
      onElevationModeChanged: updatedGis.onElevationModeChanged ?? this.state.gis.onElevationModeChanged,
      onModelSelect: updatedGis.onModelSelect ?? this.state.gis.onModelSelect,
      federatedMode: updatedGis.federatedMode ?? this.state.gis.federatedMode
    };
    this.setState({ gis: gisWithHandler });
    if (this.props.onGisPropertiesChange) {
      this.props.onGisPropertiesChange(gisWithHandler);
    }
  };

  render() {
    const serverUri = this.getActiveServerUri();

    const viewerProps = {
      ...this.getViewerCommonProps(),
      toolbarSize: this.state.toolbarSize,
      gis: this.state.gis,
      view2d: this.state.view2d,
      view3d: this.state.view3d,
      ue: this.state.ue,
      arcgis: this.state.arcgis,
      modelComposition: this.state.modelComposition,
      title: 'IafViewerExGISProjectView',
      enablePersistence: true,
      ...(serverUri && { serverUri })
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleGisPropertiesChange = this.props.onGisPropertiesChange ?? this.handleGisPropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-mapbox-viewer-container example-gis-project-view-root">
        {this.renderHeader({
          containerClassName: 'example-mapbox-viewer-header',
          contentClassName: 'example-mapbox-viewer-header-content',
          backButtonClassName: 'example-mapbox-viewer-back-button',
          toggleClassName: 'example-mapbox-viewer-toggle',
          toggleButtonClassName: 'example-mapbox-viewer-toggle-button',
          headerTextClassName: 'example-mapbox-viewer-header-text',
          subtitleClassName: 'example-mapbox-viewer-subtitle',
          title: 'GIS Project View',
          subtitle:
            'Mapbox GIS with project clustered models, federated Outline mode, and GIS-only layout (no 3D canvas).'
        })}
        {showConfigPanel && (
          <div className="example-mapbox-viewer-config-overlay" data-testid="gis-config-panel-container">
            <GisConfigPanel
              gis={this.state.gis}
              onGisChange={handleGisPropertiesChange}
              showAdvanced={true}
              onClose={handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              mapInstance={this.state.mapInstance}
            />
          </div>
        )}
        <div className="example-mapbox-viewer-content example-gis-project-view-content">
          <button
            type="button"
            className="example-gis-project-home-reset"
            onClick={this.handleGisHomeReset}
            disabled={!this.state.mapInstance}
            title="Reset GIS view (same as toolbar Home when GIS is on)"
            aria-label="Reset GIS view"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="22"
              height="22"
              viewBox="0 0 24 24"
              fill="currentColor"
              aria-hidden="true"
            >
              <path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z" />
            </svg>
          </button>
          <IafViewerDBM {...viewerProps} />
        </div>
      </div>
    );
  }
}

IafViewerExGISProjectView.propTypes = {
  ...IafViewerExMapboxStandalone.propTypes
};

export default IafViewerExGISProjectView;
`,
  "IafViewerExGISProjectView.css": `/**
 * GIS Project View — layout comes from IafViewerExMapboxStandalone.css (imported in JSX).
 * Add project-specific overrides here if needed.
 */
.example-gis-project-view-root {
  /* hook for future styling */
}

.example-gis-project-view-content {
  position: relative;
}

/* Floating Home — calls IafMapBoxGLProxy.resetAll (GIS session reset) */
.example-gis-project-home-reset {
  position: absolute;
  top: 12px;
  right: 12px;
  z-index: 10;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  padding: 0;
  border: 1px solid var(--examples-border-color, #e0e0e0);
  border-radius: 8px;
  background: var(--examples-bg-panel, #fff);
  color: var(--examples-text-primary, #333);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.12);
  cursor: pointer;
  transition: background-color 0.2s, border-color 0.2s;
}

.example-gis-project-home-reset:hover:not(:disabled) {
  background: var(--examples-bg-color, #f5f5f5);
  border-color: var(--app-accent-color, #026bfd);
  color: var(--app-accent-color, #026bfd);
}

.example-gis-project-home-reset:disabled {
  opacity: 0.45;
  cursor: not-allowed;
}
`,
  "../IafViewerExMapboxStandalone/config.js": `// GIS Configuration for Mapbox Standalone Viewer Example

// Default Mapbox token - should be replaced with actual token from environment or user input
export const GIS_CONFIG = {
  token: process.env.MAPBOX_TOKEN || "YOUR_MAPBOX_TOKEN_HERE" // Mapbox access token
};

`,
  "../IafViewerExMapboxStandalone/IafViewerExMapboxStandalone.jsx": `import React from 'react';
import PropTypes from 'prop-types';
import { IafViewerDBM } from '@dtplatform/iaf-viewer';
import { GIS_CONFIG } from './config';
import GisConfigPanel from '../toolkit/GisConfigPanel/GisConfigPanel';
import { loadCachedGisConfig } from '../toolkit/IafViewerExUtils';
import IafViewerExample from '../IafViewerExample/IafViewerExample';
import './IafViewerExMapboxStandalone.css';

class IafViewerExMapboxStandalone extends IafViewerExample {
  constructor(props) {
    super(props);
    
    // Load cached GIS config (token) from localStorage
    const cachedConfig = loadCachedGisConfig();
    
    // Merge cached values with default config
    const initialGisConfig = cachedConfig 
      ? { ...GIS_CONFIG, ...cachedConfig }
      : GIS_CONFIG;
    
    this.state = {
      ...this.state,
      gis: {
        enable: true,
        showToolbar: true,
        token: initialGisConfig.token,
        opacity: 1.0,
        dynamicRenderingZoom: 11,
        dynamicRenderingDistance: 1100,
        onIafMapReady: this.handleGisReady.bind(this),
        initial: {
          zoom: 15,
          pitch: 60,
          bearing: 0
        }
      },
      view3d: {
        opacity: 1.0,
        enable: false
      },
      view2d: {
        enable: false
      },
      ue: {
        enable: false
      },
      arcgis: {
        enable: false
      },
      showConfigPanel: props.showConfigPanel ?? false,
      eventLogs: [],
      enableEventLog: false,
      mapInstance: null
    };
  }

  handleGisReady(mapInstance) {
    this.addEventLog({
      type: 'onIafMapReady',
      mapInstance: mapInstance ? 'available' : 'null',
      info: {
        map: mapInstance?.map ? 'available' : 'null',
        containerId: mapInstance?.containerId,
        focusSelector: mapInstance?.focusSelector
      }
    });

    console.log('[Mapbox Standalone Viewer] GIS Map is ready!', mapInstance);

    this.mapInstance = mapInstance;
    this.setState({ mapInstance });

    if (mapInstance?.focusSelector) {
      const focusElement = document.querySelector(mapInstance.focusSelector);
      if (focusElement) {
        console.log('[Mapbox Standalone Viewer] GIS Map ready - focus selector available:', mapInstance.focusSelector);
      }
    }
  }


  handleGisPropertiesChange = (updatedGis) => {
    const gisWithHandler = {
      ...updatedGis,
      onIafMapReady: updatedGis.onIafMapReady ?? this.state.gis.onIafMapReady
    };
    this.setState({ gis: gisWithHandler });
    if (this.props.onGisPropertiesChange) {
      this.props.onGisPropertiesChange(gisWithHandler);
    }
  }

  render() {
    const serverUri = this.getActiveServerUri();

    const viewerProps = {
      ...this.getViewerCommonProps(),
      gis: this.state.gis,
      view2d: this.state.view2d,
      view3d: this.state.view3d,
      ue: this.state.ue,
      arcgis: this.state.arcgis,
      modelComposition: this.state.modelComposition,
      title: 'IafViewerExMapboxStandalone',
      enablePersistence: true,
      ...(serverUri && { serverUri })
    };

    const showConfigPanel = this.getShowConfigPanel();
    const handleGisPropertiesChange = this.props.onGisPropertiesChange ?? this.handleGisPropertiesChange;
    const handleConfigToggle = this.props.onConfigToggle ?? this.handleConfigToggle;

    return (
      <div className="example-mapbox-viewer-container">
        {this.renderHeader({
          containerClassName: 'example-mapbox-viewer-header',
          contentClassName: 'example-mapbox-viewer-header-content',
          backButtonClassName: 'example-mapbox-viewer-back-button',
          toggleClassName: 'example-mapbox-viewer-toggle',
          toggleButtonClassName: 'example-mapbox-viewer-toggle-button',
          headerTextClassName: 'example-mapbox-viewer-header-text',
          subtitleClassName: 'example-mapbox-viewer-subtitle',
          title: 'Mapbox Standalone Viewer',
          subtitle: 'Displays a Mapbox GIS map. Only GIS viewer is enabled.'
        })}
        {showConfigPanel && (
          <div className="example-mapbox-viewer-config-overlay" data-testid="gis-config-panel-container">
            <GisConfigPanel
              gis={this.state.gis}
              onGisChange={handleGisPropertiesChange}
              showAdvanced={true}
              onClose={handleConfigToggle}
              eventLogs={this.state.enableEventLog ? this.state.eventLogs : []}
              enableEventLog={this.state.enableEventLog}
              onEnableEventLogChange={(enabled) => this.setState({ enableEventLog: enabled })}
              mapInstance={this.state.mapInstance}
            />
          </div>
        )}
        <div className="example-mapbox-viewer-content">
          <IafViewerDBM {...viewerProps} />
        </div>
      </div>
    );
  }
}

IafViewerExMapboxStandalone.propTypes = {
  ...IafViewerExample.propTypes,
  onGisPropertiesChange: PropTypes.func
};

export default IafViewerExMapboxStandalone;

`,
  "../IafViewerExample/IafViewerExample.jsx": `import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { IafSession } from '@dtplatform/platform-api';

/**
 * Base class for all IafViewer example components
 * Provides common functionality like header height management, config panel toggling, server URI resolution,
 * event logging, model resolution, and common UI rendering helpers
 */
class IafViewerExample extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewerSettings: this._loadViewerSettingsFromStorage()
    };
  }

  _loadViewerSettingsFromStorage() {
    if (typeof localStorage !== 'undefined' && localStorage.iafviewer_settings) {
      try {
        return JSON.parse(localStorage.iafviewer_settings);
      } catch (e) {
        return undefined;
      }
    }
    return undefined;
  }

  componentDidMount() {
    this.updateHeaderHeight();
  }

  componentDidUpdate(prevProps) {
    if (prevProps.hideHeader !== this.props.hideHeader) {
      setTimeout(() => {
        this.updateHeaderHeight();
      }, 0);
    }
  }

  updateHeaderHeight = () => {
    const headerElement = this.headerRef;
    if (headerElement) {
      const headerHeight = headerElement.offsetHeight;
      const container = headerElement.parentElement;
      if (container) {
        container.style.setProperty('--header-height', \`\${headerHeight}px\`);
      }
    }
  }

  handleConfigToggle = () => {
    const currentState = this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
    const newState = !currentState;
    
    if (!this.props.onConfigToggle) {
      this.setState({ showConfigPanel: newState });
    }
    
    if (this.props.onConfigToggle) {
      this.props.onConfigToggle(newState);
    }
  }

  getActiveServerUri = () => {
    return this.props.serverUri || 
           (IafSession?.getConfig?.()?.graphicsServiceOrigin) ||
           null;
  }

  /**
   * Add an event to the event log (if event logging is enabled)
   * @param {Object} event - Event object to log
   */
  addEventLog = (event) => {
    if (!this.state.enableEventLog) {
      return;
    }
    this.setState(prevState => ({
      eventLogs: [...prevState.eventLogs, {
        ...event,
        timestamp: Date.now()
      }]
    }));
  }

  /**
   * Get the resolved showConfigPanel value (handles both controlled and uncontrolled components)
   * @returns {boolean} Whether the config panel should be shown
   */
  getShowConfigPanel = () => {
    return this.props.onConfigToggle
      ? (this.props.showConfigPanel ?? false)
      : this.state.showConfigPanel;
  }

  /**
   * Resolve the model from props (selectedItems or direct model prop)
   * @returns {Object|null} The resolved model object or null
   */
  getModel = () => {
    return this.props.selectedItems?.selectedModel || this.props.model || null;
  }

  /**
   * Common viewer props (settings + saveSettings) for IafViewerDBM.
   * Spread into viewerProps so Cache Settings in the Settings panel can persist (e.g. isSingleChannelMode).
   * @returns {{ settings: Object|undefined, saveSettings: Function }}
   */
  getViewerCommonProps = () => ({
    settings: this.state.viewerSettings,
    saveSettings: this.saveSettingsCallback
  })

  /**
   * Callback to save viewer settings to localStorage and update state.
   * Pass to IafViewerDBM as saveSettings prop so Cache Settings button persists settings.
   */
  saveSettingsCallback = (settings) => {
    if (typeof localStorage !== 'undefined') {
      localStorage.iafviewer_settings = JSON.stringify(settings);
    }
    this.setState({ viewerSettings: settings });
  }

  /**
   * Render the "No model" fallback message
   * @param {string} className - CSS class name for the container
   * @returns {JSX.Element} The "No model" fallback JSX
   */
  renderNoModelFallback = (className = 'example-viewer-no-model') => {
    return (
      <div className={className}>
        <p>No model selected. Please select a model from the Navigator to view this example.</p>
      </div>
    );
  }

  /**
   * Render the common header structure (Back button, View mode toggle, Title/Subtitle)
   * @param {Object} options - Header configuration options
   * @param {string} options.containerClassName - CSS class for the header container
   * @param {string} options.contentClassName - CSS class for the header content
   * @param {string} options.backButtonClassName - CSS class for the back button
   * @param {string} options.toggleClassName - CSS class for the view mode toggle container
   * @param {string} options.toggleButtonClassName - CSS class for the toggle buttons
   * @param {string} options.headerTextClassName - CSS class for the header text container
   * @param {string} options.subtitleClassName - CSS class for the subtitle (optional, defaults to headerTextClassName + '-subtitle')
   * @param {string} options.title - Header title
   * @param {string} options.subtitle - Header subtitle
   * @returns {JSX.Element} The header JSX
   */
  renderHeader = ({
    containerClassName,
    contentClassName,
    backButtonClassName,
    toggleClassName,
    toggleButtonClassName,
    headerTextClassName,
    subtitleClassName,
    title,
    subtitle
  }) => {
    if (this.props.hideHeader) {
      return null;
    }

    const finalSubtitleClassName = subtitleClassName || \`\${headerTextClassName}-subtitle\`;

    return (
      <div className={containerClassName} ref={(el) => { this.headerRef = el; }}>
        <div className={contentClassName}>
          <button 
            className={backButtonClassName}
            onClick={() => {
              if (this.props.onBackToList) {
                this.props.onBackToList();
              } else if (this.props.history) {
                this.props.history.push('/navigator?examplesView=true');
              } else {
                window.location.hash = '/navigator?examplesView=true';
              }
            }}
          >
            ← Back to Examples
          </button>
          {this.props.onViewModeToggle && (
            <div className={toggleClassName}>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'demo' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('demo')}
              >
                Demo
              </button>
              <button 
                className={\`\${toggleButtonClassName} \${this.props.viewMode === 'code' ? 'active' : ''}\`}
                onClick={() => this.props.onViewModeToggle('code')}
              >
                Code
              </button>
            </div>
          )}
          <div className={headerTextClassName}>
            <h1>{title}</h1>
            {subtitle && <p className={finalSubtitleClassName}>{subtitle}</p>}
          </div>
        </div>
      </div>
    );
  }
}

IafViewerExample.propTypes = {
  hideHeader: PropTypes.bool,
  showConfigPanel: PropTypes.bool,
  onConfigToggle: PropTypes.func,
  serverUri: PropTypes.string,
  selectedItems: PropTypes.object,
  model: PropTypes.object,
  history: PropTypes.object,
  onBackToList: PropTypes.func,
  viewMode: PropTypes.string,
  onViewModeToggle: PropTypes.func
};

export default IafViewerExample;

`
};
